### ISSUE TITLE
Chapter 4

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#103]
In Chapter 4 for its said that the conceptual model is a physical structure, that breaks rule 3.1 and 3.2 and should be an implementation issue.

**Comment by kuldaraas** [comment]
It says that the conceptual model is to be IMPLEMENTED as a physical structure. I suppose this is still valid and as such there is no need for changing the meaning of the sentence. 

Do you think the sentence should be rephrased somehow? 

The current exact sentence:
"The implementation of the conceptual model described in Requirement 3.6 is a fixed physical (folder) structure which follows exactly the conceptual structure."

**Comment by karinbredenberg** [comment]
Why have options if its going to be forced to be a physical structure? For the high level as the CS IP is these options should be open and we describe the possible ways of doing it and then you choose when you implement which way you do it. In the profiles for SIP, AIP and DIP its then implemented as physical structure.

**Comment by karinbredenberg** [comment]
Text update made and needs review.
