### ISSUE TITLE
All document references should provide a specific location

### ISSUE THREAD

**Issue by carlwilson** [DILCISBoard/E-ARK-CSIP#105]
Currently the document references other documents without providing a resolvable link, some of these are DILCIS and E-ARK documents, using a "all Xxtype documents can be found on the Ysite http:y.com" style message. We shouldn't force the reader to search for referenced documents on websites.

**Comment by PhillipTommerholt** [comment]
Examples in: 

http://earkcsip.dilcis.eu/#14-relation-to-other-documents 
http://earkcsip.dilcis.eu/#12-the-common-specification-for-information-packages-and-content-information-type-specifications 

Probably more examples in other sections

**Comment by carlwilson** [comment]
Me to review references as part of final pre-publication pass.
