### ISSUE TITLE
Use "Section" rather than "Chapter"

### ISSUE THREAD

**Issue by carlwilson** [DILCISBoard/E-ARK-CSIP#106]
Chapter is usually a part of a book, specifications have parts and sections.

**Comment by PhillipTommerholt** [comment]
"Chapter" is mentioned 26 times - all in the columns named "Description & usage" in the requirement tables.

**Comment by PhillipTommerholt** [comment]
Perhaps we should change:

"The ID must follow the rules for xml:id described in the chapter of the textual description of CSIP named “General requirements for the use of metadata”

to 

"The ID must follow the rules for xml:id described in "[The use of identifiers](http://earkcsip.dilcis.eu/#the-use-of-identifiers)".

**Comment by carlwilson** [comment]
Chapter has gone.
