### ISSUE TITLE
There are no Content Information Type Specifications

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#108]
On page 9 in CSIP:

> For now (February 2017) there are seven Content Information Type Specifications which have been created by the E-ARK project and have been verified for usage within the Common Specification:

I don't think this is entirely correct. We for example never created a Content Information Type Specification for relational databases. We did a lot of work with Content Information Types and you can find a lot of details  for relational databases in the SIP specification and the DIP specification and in the Pilot documentation - but that is it. There is no document for databases where the full specification has been formalized. 

In Section 6 in CSIP it is described how new Content Information Type Specifications can be made and I guess that possible new Content Information Type Specifications should be  individual documents seperate from CSIP, CSSIP, CSAIP, and CSAIP? If so I think it is important that the CSSIP and CSDIP gets stripped of the details and only make requirements as to how to identify which Content Information Type Specification the current IP is said to comply to?

**Comment by karinbredenberg** [comment]
I agree with Phillip regarding the writing about Content Informations Types in the profile for SIP, AIP and DIP. It shouldnt be there, they are their own documents and the important part is how CS IP reference them as well as the naming of them gets correct in the SIP, AIP and DIP.

**Comment by PhillipTommerholt** [comment]
Anders Bo and I are responsible for the DIP specification.
We can easily remove the Content Information Type (CIT) parts from the specification, but we need people responsible for the CIT Specifications. I see the CIT Specifications as the best selling point for the E-ARK common specifications, as these tell other partners how "something" (like databases) should be stored as a CSIP.

**Comment by karinbredenberg** [comment]
We do have responsible persons for the CIT in the DILCIS Board. More text regarding that will come to the DILCIS Board webpage.

**Comment by carlwilson** [comment]
Not sure there's a resolution for this, @PhillipTommerholt  feel free to reopen with more info if needed.
