### ISSUE TITLE
Rename index.md to README.md?

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#120]
@carlwilson Is there a reason why the entry point for the documentation in markdown is called index.md? Github works a lot better if you call it README.md as it opens it right away.

To your consideration.

**Comment by carlwilson** [comment]
Hi @jmaferreira, this is so that we get nice GitHub pages URL's and is really for the site content. It still needs a README.md but that should talk about the GItHub repo not the specification itself.

**Comment by carlwilson** [comment]
Hi @jmaferreira we've now got the beginnings of a README document which I'll be fleshing out a little more, if then intention's clear and OK I'd like to close this if possible?

**Comment by jmaferreira** [comment]
Please do. It clear now.
