### ISSUE TITLE
Visual appearance: Should we manually word wrap XML?

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#127]
Visual appearance: Should we manually word wrap XML in order to make it fit on size A4 portrait?
I have done it for section 6.2 (in its own branch), but I hope we do not have to do it, and just leave it as is.

**Comment by koit** [comment]
I prefer no manual wrapping as it makes it harder to read in browsers and this is where we spend most of our time with CSIP.

If wrapping ends up being necessary, it should be done right before the creation of the print file, on a separate branch. There might be automated tools for wrapping and the exact line length will depend on typeface and font size choices, so earlier manual wrappings might need to be redone at print time.

**Comment by carlwilson** [comment]
I'd vote for no wrapping, it's a little arbitrary and can lead to unnecessarily "hard" decisions as to where to break lines.

**Comment by andersbonielsen** [comment]
No manual word wrapping
