### ISSUE TITLE
altRecordID - we should consider describing the optional use it

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#129]
https://github.com/DILCISBoard/E-ARK-CSIP/blob/master/specification/implementation/metadata/#532-use-of-the-mets-header-element-metshdr

We should consider describing the optional use of https://www.loc.gov/standards/mets/docs/mets.v1-7.html#altRecordID

There is a need for human readable and memorable IDs in managing IPs, esp. SIPs when handling errors.

**Comment by karinbredenberg** [comment]
Something to handle in a local extension. A description of how to create extension profiles should be a part of work of a continuation project.
