### ISSUE TITLE
IP with no representations - is it allowed?

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#130]
**There is no explicit declaration of the minimum number of representations, but implicit evidence points to minimum being one. Whatever the decision, it should be clearly stated.**

Zero seems to be a better choice than one, as it allows transporting of metadata without content files. This is actively used in Estonia for transferring the archival descriptions of paper records from the record producers to the national archives.

Ch. 4.1 [CSIPSTR10](https://github.com/DILCISBoard/E-ARK-CSIP/blob/master/specification/implementation/structure/index.md#CSIPSTR10) is an example of the vagueness:

> CSIPSTR10: The `representations` folder MUST include a sub-folder for each individual representation (i.e. the “representation folder”) named with a string uniquely identifying the representation within the scope of the package (for example the name of the representation and/or its creation date could be good examples for an representation sub-folder) ;

Also, all IP diagrams have at least one IP.

Referenced CSIP version: [a84d77a](https://github.com/DILCISBoard/E-ARK-CSIP/tree/a84d77aa54244e8305904de65cbdd2539319300a), 2018-09-11

**Comment by karinbredenberg** [comment]
Update is on its way, not ready yet.

**Comment by karinbredenberg** [comment]
Connected with #71

**Comment by PhillipTommerholt** [comment]
This might also have connections to how we are segmenting IPs.
In the current recommendation we have a "Master IP" with no representations.
See https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/considerations/#625-illustration-of-references-between-mets-files-in-a-segmented-ip

**Comment by jmaferreira** [comment]
We would like to have packages without representations.

**Comment by karinbredenberg** [comment]
Use of no representations will be possible. Updates will be made in CS IP text and METS profile.

**Comment by karinbredenberg** [comment]
Handled
