### ISSUE TITLE
Use "SHOULD" instead of "recommended"

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#131]
To minimise ambiguity, CSIP should say **"It SHOULD be ..."** instead of **"It is recommended that it be ..."**

A specific example is Ch 5.3.1 [CSIP2](https://github.com/DILCISBoard/E-ARK-CSIP/blob/master/specification/implementation/metadata/index.md#CSIP2) `mets/@OBJID`, which currently reads:
>It is recommended that it be the same as the name or ID of the package (the name of the root folder)

Referenced CSIP version: [a84d77a](https://github.com/DILCISBoard/E-ARK-CSIP/tree/a84d77aa54244e8305904de65cbdd2539319300a), 2018-09-11

**Comment by karinbredenberg** [comment]
Text update will come when the METS profile is ready.

**Comment by PhillipTommerholt** [comment]
There are two requirements "hidden" in the text:

> In addition to the attributes the METS root element mets MUST define all relevant namespaces and locations of XML schemas using the @xmlns and @xsi:schemaLocation attributes.
> 
> In case XML schemas have been included into the package (i.e. placed into the schemas folder) it is recommended to link to the schemas using the relative path of the schema file (i.e. schemas/mets.xsd).

**Comment by karinbredenberg** [comment]
Information regarding @OBJID have been updated. Its now CSIP1.
