### ISSUE TITLE
CSIP4 CONTENTTYPESPECIFICATION - who can extend the vocabulary?

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#132]
Ch 5.3.1 [CSIP4](https://github.com/DILCISBoard/E-ARK-CSIP/blob/master/specification/implementation/metadata/index.md#CSIP4) `mets/@CONTENTTYPESPECIFICATION` has this sentence in the end:
> NB The vocabulary is extensible as additional content information type specifications are developed.

**The vocabulary is extensible by whom?**

Referenced CSIP version: [a84d77a](https://github.com/DILCISBoard/E-ARK-CSIP/tree/a84d77aa54244e8305904de65cbdd2539319300a), 2018-09-11

**Comment by karinbredenberg** [comment]
Update will state that the vocabulary is owned by the DILCIS Board.

**Comment by jmaferreira** [comment]
From DCMI (http://www.dublincore.org/documents/dcmi-type-vocabulary/)

Collection , Dataset , Event , Image , InteractiveResource , MovingImage , PhysicalObject , Service , Software , Sound , StillImage , Text

**Comment by karinbredenberg** [comment]
There are two suggested lists, [http://www.loc.gov/preservation/resources/rfs/TOC.html](http://www.loc.gov/preservation/resources/rfs/TOC.html) and [http://www.dublincore.org/documents/dcmi-type-vocabulary/](url) and these two can be merged.

**Comment by karinbredenberg** [comment]
Handled
