### ISSUE TITLE
CSIP6 PROFILE - improve wording, switch "has to have" to MoSCoW

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#133]
Ch 5.3.1 [CSIP6](https://github.com/DILCISBoard/E-ARK-CSIP/blob/master/specification/implementation/metadata/index.md#CSIP6) `mets/@PROFILE` includes the text:
> The PROFILE attribute has to have as its value the URL of the used profile. When this profile is implemented as is the value is the URL for the official CS IP METS Profile.

Two issues with that:
1. The second sentence is unclear
2. "has to have as its value" is unclear, we should switch to MUST or SHOULD

I propose replacing the two sentences with one: **"The value SHOULD be a URL that points to the Information Package profile that is used."**

I chose SHOULD because it seems to be a bit softer requirement, illustrated by the fact that http://www.eark-project.com/METS/IP.xml in the example points to nothing.

Also, implicit in my proposal is that the value can also be a non-URL, e.g.:
`<mets PROFILE = "National Archives of Wakanda IP profile">`

If we demand URLs, the rule should be: **"The value MUST be a URL and it SHOULD point to the Information Package profile that is used."**

Referenced CSIP version: [a84d77a](https://github.com/DILCISBoard/E-ARK-CSIP/tree/a84d77aa54244e8305904de65cbdd2539319300a), 2018-09-11

**Comment by karinbredenberg** [comment]
Update states that it needs to be the URL of the used profile. 
Text update will come when the METS profile is ready.

**Comment by PhillipTommerholt** [comment]
Partially solved.

"Has to have" still needs to be transformed to SHOULD or MUST.
