### ISSUE TITLE
Remove sentence in 6.2.1

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#137]
Remove 

> "According to the E-ARK Common Specification for IPs an IP can have several representations. All representations contain the same intellectual content, but as the name implies is another representation; in its most simple form this could be another file format such as TIFF instead of JPEG." 

from:
https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/considerations/#621-the-structure-for-ip-their-representations-and-their-segments

It is a leftover from the time the recommendation was not part of CSIP and I don't see that it makes any added value. At least it should be reformulated.

**Comment by karinbredenberg** [comment]
Has been removed
