### ISSUE TITLE
Segmenting conflict with CSIPSTR1

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#138]
[This](https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/structure/#41-folder-structure-of-the-cs-ip):

> CSIPSTR1: Each CS IP Information Package MUST be included in a single physical folder (i.e. the “Information Package folder”). In other words: on the highest structural level a Common Specification IP MUST consist of one and only one folder;

is not possible if we need to segment an IP. I am not sure how to handle this @karinbredenberg : should we keep CSIPSTR1 as is, and then state in 6.2 something like "if CSIPSTR1 can not be met, then this segmenting recommendation follows"? Or should there also be a link to 6.2 after the CSIPSTR1?

**Comment by PhillipTommerholt** [comment]
Since CSIPSTR1 is in conflict with Principle1.4 I tend to believe that we should reformulate CSIPSTR1. Maybe from MUST to SHOULD?

**Comment by karinbredenberg** [comment]
Handled
