### ISSUE TITLE
Same "form" in principles for information packages

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#139]
Here are some deviations in the form in the principles https://dilcisboard.github.io/E-ARK-CSIP/specification/specification/requirements/#31-general-principles:

___________________________________
1)
Sometimes CS IP states that: 

> **any** CS IP MUST xxxx

Sometimes CS IP states that:

> **a** CS IP MUST xxxx

Sometimes CS IP states that:
> The structure of **the** Information Package SHOULD

I guess there is no difference between "any" or "a" or "the" and that we ought to use the same?
_________________________
2)
Sometimes CS IP states that: 

> A **Common Specification Information Package** MUST xxxx

Sometimes CS IP states that: 

> A **CS IP Information Package** MUST xxxx

Sometimes CS IP states that: 

> The structure of the **Information Package** SHOULD xxxx

I guess we should stick to one form for an information package that conform to CS IP?

_______________
3)
One specific principle varies a lot from the other ones:

> Principle 1.3
> The CS IP MUST NOT define the scope of data and metadata which constitutes an Information Package.

Here I understand the principle as a principle that only goes for the CS IP itself? Since we are the authors of the CS IP I guess we can make sure to implement this. We should reformulate so it is a principle for a CS IP Information Package and not the CS IP.

**Comment by shsdev** [comment]
1 and 2: agreed, some harmonization is required here.
3: Maybe, what was meant here is that any instance of a CS IP, so "a CS IP", must not ...

**Comment by karinbredenberg** [comment]
Check that this has been implemented now in the principle updated

**Comment by PhillipTommerholt** [comment]
This still needs an overhaul.

**Comment by karinbredenberg** [comment]
Fixing needed when we start the updating after review.

**Comment by carlwilson** [comment]
Hi @PhillipTommerholt there's been a lot of work on use of clauses and expunging use of "CS IP" since now. Would you like a chance to review before closing this issue.
