### ISSUE TITLE
"Root level METS" and "Representation level METS" - overlap/redundancy?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#140]
There are two requirements in section 4.1 https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/structure/#41-folder-structure-of-the-cs-ip:

> CSIPSTR4: The Information Package folder MUST include a metadata file named METS.xml, which includes information about the identity and structure of the package and its components

> CSIPSTR12: The representation folder CAN include a metadata file named METS.xml which includes information about the identity and structure of the representation

Is the missing _"and its components"_ in CSIPSTR12 a deliberate choice? Does this mean that all files (=components?) must be listed in the "Root level METS" and not in the  "Representation level METS"?

I am working on the Northwind example where all the files in the representation is listed in the "Representation level METS" but they are not listed in the "Root level METS". I prefer this way, but I need to make sure that this is valid @karinbredenberg, and if so, CSIPSTR4 and CSIPSTR12 should be aligned.

In terms of validation, I might believe that CSIP should be more deliberate on this issue @carlwilson ?
_Edit: I mean: how would a validator know where to look for filesecs and make checksum-checks in a package?_

**Comment by andersbonielsen** [comment]
Should we reduce the options? An demand always to have a representation METS?

Here in the text from section 5.1:
https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#51-general-requirements-for-metadata-in-a-cs-ip-information-package
> Some of the core metadata requirements are already visible from the structure presented in the previous Section. Most crucially the CS IP requires that all Information Packages MUST include one and only one METS file in the Information Package folder of the package, named METS.xml. In addition, the package CAN include one METS.xml file in each of the representation folders. These files will be referred to as “root METS” and “representation METS” respectively in the rest of this document. The detailed specification of using METS within the CS IP is available in Section 5.3.

**Comment by shsdev** [comment]
I would say that the "and its components" can refer to both cases, the representation files either being in the single METS or in the represenation METS files. It does not mean that all files must be listed in the root METS.

CSIPSTR12 states that an IP CAN contain more than just the Root level METS, i.e. the Representation level METS. CSIPSTR4 and  CSIPSTR12 are consistent.

**Comment by andersbonielsen** [comment]
No, because CSIPSTR4 refers only to the Information Package folder (root mets).
I would suggest we skip the "and its components" from CSIPSTR4.
In fact we may add all of "and its components" to CSIPSTR12 to make certain that the information is there and not partially in the root mets.
Or maybe something better can be specified?

**Comment by carlwilson** [comment]
I thought that first part of CSIPSTR12 would read: "The representation folder SHOULD include a metadata file...", making this a recommendation, but not mandatory.

**Comment by PhillipTommerholt** [comment]
You are right Carl. Updated suggestion:
__________________________
CSIPSTR4: The Information Package folder MUST include a metadata file named METS.xml, which MUST include information about the identity and structure of the package and its components at a minimum down to a general description or mention of each representation. It CAN include information about the structure of each representation and its components.

CSIPSTR12: The representation folder SHOULD include a metadata file named METS.xml which then MUST include information about the identity and structure of the representation and its components.
______________________________________________

**Comment by karinbredenberg** [comment]
Handled
