### ISSUE TITLE
CSIP2 - does not describe purpose

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#141]
CSIP2 - does not describe the purpose.
https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#531-use-of-the-mets-root-element-element-mets

![image](https://user-images.githubusercontent.com/15984159/46850752-59ad2080-cdf5-11e8-9175-c9c097c3ebf8.png)

It is an ID for what?
In the Northwind example we have a "Root level METS" and "Representation level METS". In the "Root level METS" we give the ID of the package and in the "Representation level METS" we give the ID of the representation folder. But if we follow the current CSIP2, then the "Representation level METS" should also give the ID of the package? Or doesn't this interfere with the OBJID being unique across the repository? How should the last sentence be interpreted? That the ID-package should be unique at least across the repository or that every OBJID-element in all METS-files should be unique?

**Comment by karinbredenberg** [comment]
Rewording in it so the representation has its "root folder" name or ID as the OBJID solves the problem?

**Comment by PhillipTommerholt** [comment]
> Rewording in it so the representation has its "root folder" name or ID as the OBJID solves the problem?

Yes, I believe so.

**Comment by karinbredenberg** [comment]
Handled
