### ISSUE TITLE
Explanation for namespace DILCIS needed - at some point in time

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#142]
5.3.1 xmlns:csip="DILCIS"

https://github.com/DILCISBoard/E-ARK-CSIP/blob/master/specification/implementation/metadata/index.md#531use-of-the-mets-root-element-element-mets

We should explain the use of the namespace DILCIS with the abbreviation csip.

**Comment by karinbredenberg** [comment]
Part of the profile. And should be added into the text.

**Comment by karinbredenberg** [comment]
Handled
