### ISSUE TITLE
Set default namespace to mets in the example?

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#143]
https://github.com/DILCISBoard/E-ARK-CSIP/blob/master/specification/implementation/metadata/index.md#531use-of-the-mets-root-element-element-mets

```xml
<mets:mets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:mets="http://www.loc.gov/METS/"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:csip="DILCIS"
```

Why not set the default namespace to be mets? And then remove the prefix mets from mets:mets?
```xml
xmlns="http://www.loc.gov/METS/" 
```

**Comment by karinbredenberg** [comment]
I would say that for always making it easy to read to always have prefix on all elements including the mets ones.

**Comment by carlwilson** [comment]
We have #228 open which covers this.
