### ISSUE TITLE
CSIP15 and CSIP16 - cardinality

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#144]
Both CSIP15 and CSIP16 states that attributes are mandatory - but their cardinalities are 0..1

https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#532-use-of-the-mets-header-element-metshdr

![image](https://user-images.githubusercontent.com/15984159/46850722-32eeea00-cdf5-11e8-8a2c-177240441b34.png)

**Comment by karinbredenberg** [comment]
That solves itself with the updated profile which describes the agent with more elements.

**Comment by karinbredenberg** [comment]
Handled
