### ISSUE TITLE
CSIP4 and CSIP5 does not have csip: -prefixes

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#145]
In the requirements further down in CSIP there are csip:-prefixes on the extra attributes in the markdown-tables and the examples (se CSIP11 and CSIP19). 

For CSIP4 and CSIP5 this is only the case in the example. Should they also have csip:-prefixes in the markdown-table?

https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#531-use-of-the-mets-root-element-element-mets

**Comment by karinbredenberg** [comment]
Handled
