### ISSUE TITLE
CSIP19 - mets/metsHdr/agent/note can't have attributes

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#146]
I am looking at CSIP19 in my work on updating the Northwind example under following section
https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#532-use-of-the-mets-header-element-metshdr .

Issue 1:
The mets schema defines the note-element as a element which can't have attributes, so I can't add attributes without causing a validation error.

Minor Issue 2:
The markdown-table and the following example are not identical. The markdown-table states that the attribute should be called @csip:NOTETYPE. The following example is called csip:TYPE

Image:
![image](https://user-images.githubusercontent.com/15984159/46803781-2d47c480-cd61-11e8-84f5-ca3d6ef718fa.png)

XML:
```xml
<mets:note csip:TYPE="SOFTWARE VERSION">2.1.0-beta.7</mets:note>
```

**Comment by karinbredenberg** [comment]
You need to use the version 1.12 of the schema where the attribute is added.
I'll update in the profile.

**Comment by karinbredenberg** [comment]
Looks like all namespace prefixes gets omitted in the transformation.

**Comment by carlwilson** [comment]
We already have issues for namespace loss in transformation so closing.
