### ISSUE TITLE
Clarification of IDs

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#147]
CSIP states following in section 5.2
https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#the-use-of-identifiers

> The ID data type in XML does define that a legit value must begin with a letter, or the underscore character (‘_’), and contain no characters other than letters, digits, hyphens, underscores, full stops, and certain combining and extension characters. To overcome this limitation and in order to allow for interoperable package identification all identifiers within Common Specification metadata MUST start with a prefix, followed by the actual value of the identifier.

1:
Is it an idea to provide a link to the standard where this prerequisite is stated? 

2:
Also, I think we should be more clear if it only goes for ID attributes called ID as in the examples, or are other IDs such as for example the mets @OBJID also requried to have a prefix?

**Comment by karinbredenberg** [comment]
Its the xml standard itself that has that demand... [https://www.w3.org/TR/xml-id/](url)

It only goes for ID's with the type xml:id

**Comment by andersbonielsen** [comment]
Yes, regarding 1, I think we should clarify that for the reader by mentioning it or by ref. to the XML standard.

**Comment by karinbredenberg** [comment]
There are text in the textual part of CS IP already, the links need to be added there though. In the profile (and then in the tables) there are a remark regarding the lement being an xml:id and a referene to that text in the textual document.

**Comment by PhillipTommerholt** [comment]
I have labeled this issue "Ready" to close @shsdev 
I can't remember if there was a decision or discussion but the text in the CS IP states the following now:

![image](https://user-images.githubusercontent.com/15984159/52121160-ea1aa580-261e-11e9-841e-f59c01e13426.png)

Is this okay - or is there still a need to define a prefix more explicit?

**Comment by karinbredenberg** [comment]
Handled.
