### ISSUE TITLE
METS files need to follow the official METS Schema version 1.11  - MoSCoW?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#148]
Section 5.3 https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#53-use-of-mets the first sentence states:

> The main requirement for METS files in a CS IP Information Package is that these need to follow the official METS Schema version 1.11 .

I guess that this sentence need to be isolated to a MoSCoW requirement with an ID as the rest of the requirements?

**Comment by karinbredenberg** [comment]
The current standard used is METS and the schema now is version 1.12. We should perhaps omit the version number?
