### ISSUE TITLE
CSIP15 reads ambiguously

### ISSUE THREAD

**Issue by carlwilson** [DILCISBoard/E-ARK-CSIP#151]
Reading the requirement [CSIP15](https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#CSIP15) leaves me a little wooly headed. It reads
> The CS IP requires that at least one instance of the agent element includes the `agent/@TYPE` attribute with the value “OTHER”. In other occurrences of the agent element the attribute is optional. If used, values defined in official METS documentation shall be followed (“individual”, “organisation”, “other”).

The cardinality is `0..1` but the wording leads me to believe that there MUST be one occurrence given there has to be a `metsHdr/agent` element, see [CSIP12](https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#CSIP12)

**Comment by PhillipTommerholt** [comment]
Related to this issue: https://github.com/DILCISBoard/E-ARK-CSIP/issues/144

**Comment by karinbredenberg** [comment]
Handled
