### ISSUE TITLE
Dependencies suggest that cardinality of CSIP83 is misleading

### ISSUE THREAD

**Issue by carlwilson** [DILCISBoard/E-ARK-CSIP#152]
Requirement [CSIP83](https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#CSIP83) states:
> Each folder (and sub-folder) within the package must be represented by an occurrence of the `<div>` element. Please note that sub-folders must be represented as nested div elements.
Example:
`<structMap TYPE="physical" LABEL="CS IP StructMap">`
`<div LABEL="Package123">`
`<div LABEL="metadata">`

The cardinality is `0..1` BUT we mandate the presence of some folders, e.g "representations" and "data" meaning that there should always be at least two `div` elements to match these folders?

**Comment by karinbredenberg** [comment]
Total rewrite if this is on the way in the METS profile.

**Comment by jmaferreira** [comment]
I think this is a repetition of issues #154 and #153

**Comment by karinbredenberg** [comment]
And the structMap is also restructured so this issue is perhaps obsolete?

**Comment by karinbredenberg** [comment]
Handled
