### ISSUE TITLE
Cardinality for CSIP83 - Structural divisions 	structMap/div

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#153]
https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#536-use-of-the-mets-structural-map-element-structmap
The cardinality for CSIP83 is stated as 0..n
With the wording:
> Each folder (and sub-folder) within the package must be represented by an occurrence of the <div> element. Please note that sub-folders must be represented as nested div elements.
the cardinality must be 1..n

**Comment by karinbredenberg** [comment]
Total rewrite of the structMap requirements is on its way.

**Comment by karinbredenberg** [comment]
Handled
