### ISSUE TITLE
CSIP83 - should/must/must not/ the root package folder be identified in structMap/div

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#154]
https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#536-use-of-the-mets-structural-map-element-structmap

Related to #153 

> CSIP83 | Structural divisions | structMap/div | Each folder (and sub-folder) within the package must be represented by an occurrence of the \<div> element. Please note that sub-folders must be represented as nested div elements. Example: \<structMap TYPE="physical" LABEL="CS IP StructMap"> \<div LABEL="Package123">     \<div LABEL="metadata"> | 0..n

CSIP83 wording is 
> within the package 

But the example in the specification row and the example below the spc. table does not limit itself to folders _within_ the package. It includes the root package folder itself - with the label "Package123" in the example in the spec. row and with the label  "uuid-4422c185-5407-4918-83b1-7abfa77de182" in the example below the spec. table.

```xml
<mets:structMap ID="uuid-1465D250-0A24-4714-9555-5C1211722FB7" TYPE="physical" LABEL="CS IP StructMap">
    <mets:div ID="uuid-638362BC-65D9-4DA7-9457-5156B3965A17" LABEL="uuid-4422c185-5407-4918-83b1-7abfa77de182">
        <mets:div ID="uuid-A4E1C5B6-CD9B-43EF-8F0C-3FD3AB688F80" LABEL="metadata"> 
```

It does seem beneficial to specify the full folder structure - and if so we should change the wording about 
> within the package 

Next, we have to clarify the relationsship between the ID of the IP,  the value of the mets/@OBJID and the value of the structMap/div/@ID and the name of folder  - see CSIP2

**Comment by karinbredenberg** [comment]
Text update will be made in the METS profile.

**Comment by karinbredenberg** [comment]
Handled
