### ISSUE TITLE
Better explanation of the relation between the value of the ID of the IP, the value of mets/@OBJID and structMap/div/@LABEL

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#155]
I find that we need a more elaborate explanation of the relation between the value of the ID of the IP, the value of mets/@OBJID and the value of the structMap/div/@LABEL.

It is stated in CSIP2, CSIP84 and CSIP85, but it is difficult to understand and explain.
We should maybe explain that because IDs by nature have to be unique within the mets file the value of the OBJID cannot be the same as the vaule of ID.
Is there another place where we can explain about these relations?

CSIP2 | Content ID | mets/@OBJID | Mandatory in this specification. It is recommended that it be  the same as the name or ID of the package (the name of the root folder).  The OBJID must meet the principle of being unique at least across the  repository | 1..1
-- | -- | -- | -- | --

CSIP84 | Structural division ID | structMap/div/@ID | Mandatory, identifier must be unique within the package | 1..1
-- | -- | -- | -- | --

CSIP85 | Structural division name | structMap/div/@LABEL | Mandatory, value must be the name of the folder (“metadata”,  “descriptive”, “schemas”, “representations”, etc). The LABEL value of  the first div element in the package is the ID of the package | 1..1
-- | -- | -- | -- | --

**Comment by karinbredenberg** [comment]
There are an example of ID is the beginning of the text. Regarding the different requirements mentioned here, the latest text for them are in the profile currently in the google drive and I'm working on version 4 and when I've added the new structMap and the other decisions made it will be uploaded to Git.
