### ISSUE TITLE
CSIP3 requirements for TYPE attribute should be more prescriptive

### ISSUE THREAD

**Issue by carlwilson** [DILCISBoard/E-ARK-CSIP#156]
[CSIP3](https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#CSIP3) concerns the `mets/@TYPE` attribute and it states:
> Mandatory in this specification. The `TYPE` attribute must be used for identifying the type of the package (genre), for example ERMS, RDBMS, digitised construction plans. However, there is no fixed vocabulary and as such implementers are welcome to use values most suitable for their needs.

We should explicitly prohibit empty and all whitespace values.

**Comment by karinbredenberg** [comment]
Update comes with the new version of the profile.

**Comment by jmaferreira** [comment]
I'm not sure what help is needed here.

**Comment by karinbredenberg** [comment]
We have a value list to use now so this issue is gone?

**Comment by karinbredenberg** [comment]
Handled
