### ISSUE TITLE
One or multiple requirements per METS-element?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#157]
In CSIP15 and CSIP16 https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#532-use-of-the-mets-header-element-metshdr (which is up to revision https://github.com/DILCISBoard/E-ARK-CSIP/issues/144) there are multiple requirements in a single CSIP requriement (where mandatory values are given in the decription of the requirement).

In https://dilcisboard.github.io/E-ARK-CSIP/specification/implementation/metadata/#533-use-of-the-mets-descriptive-metadata-section-element-dmdsec there are several CSIPs that goes for the same element, where the mandatory values have there own CSIP-IDs

I think the best way is to make sure that all requirements follow the "same structure". 
(This issue is hard to formulate - please ask questions where it is unclear)

**Comment by karinbredenberg** [comment]
Have been taken care of in the METS profile.

**Comment by jmaferreira** [comment]
The requirements table is totally broken.
Needs to be generated again or fixed manually.

![screenshot 2018-11-20 at 15 12 29](https://user-images.githubusercontent.com/3181302/48782757-cd84f780-ecd6-11e8-93df-d9ecba91f3da.png)

**Comment by karinbredenberg** [comment]
Handled
