### ISSUE TITLE
Incoherence between principles definition (section 3; wording)

### ISSUE THREAD

**Issue by hsilva-keep** [DILCISBoard/E-ARK-CSIP#172]
E.g. at https://carlwilson.github.io/E-ARK-CSIP/specification/specification/requirements/#32-identification-of-the-information-package

- Principle 2.3: Any CS IP Information Package MUST bear an identifier which is unique and persistent within the repository.
- Principle 3.1: A Common Specification Information Package MUST be built in such a way that its data and metadata can be logically separated from one another.

**CS IP Information Package** vs. **Common Specification Information Package**

This is only valid for principles 3.1 until 3.4 (inclusive), while the rest of the principles are coherent.

**Comment by carlwilson** [comment]
Look for and expunge repetition around acronym, i.e. search for CSIP Information..
