### ISSUE TITLE
CSIPSTR12: don't agree with MoSCoW classification

### ISSUE THREAD

**Issue by hsilva-keep** [DILCISBoard/E-ARK-CSIP#177]
https://carlwilson.github.io/E-ARK-CSIP/specification/implementation/structure/folders/

*CSIPSTR12: The representation folder CAN include a metadata file named METS.xml which includes information about the identity and structure of the representation;*

If a representation folder exists, then METS.xml for the representation MUST exists otherwise how can one know the contents of the representation??? E.g. for validation???

**Comment by PhillipTommerholt** [comment]
Hi Helder
we discussed this in a previous A2 meeting, and the formulation of CSIPSTR12 has been changed... see https://github.com/DILCISBoard/E-ARK-CSIP/issues/140

**Comment by hsilva-keep** [comment]
@PhillipTommerholt **SHOULD** is not mandatory & without METS.xml at representation level one does not know the contents of the representation. Do you agree?

**Comment by PhillipTommerholt** [comment]
I am in favor of a requirement that states that a METS.xml MUST be in a representation :) 
But I guess the formulation ended with should, since it is a possibility that the whole package is described in the root METS.xml. I am looking forward to discuss this with you on the next A2 meeting - maybe we can convince all that this should be a MUST.

**Comment by hsilva-keep** [comment]
@PhillipTommerholt I don't agree with that either, i.e., that the whole package is described in the root METS.xml...

**Comment by kuldaraas** [comment]
The intention during E-ARK was that these two req's express the possibility of either describing the whole package in one root METS file or using (besides root METS) the representation METS's to achieve more scalability. 

If this intention is still valid then are we missing a statement about duplication in the req's: "the information in root + rep METS files must at all times be complete; information in root + rep METS files must not be duplicated"?

Btw, I personally would also prefer to have a more strict req - do not allow both situations (with or without rep METS) but decide strictly on using just one. But I think it'd be hard to reach an agreement here as both solutions have their positive sides (simplicity and integrity of root METS vs scalability of rep METS) .

**Comment by hsilva-keep** [comment]
@kuldaraas I must be sincere, I wouldn't like (technically speaking) to implement both ways. The same way we ditched simple/basic structure (i.e. possibility to have files right beneath representation folder as opposite of being inside data folder), I also think we should be strict about having to describe the representations in their own METS files.

**Comment by karinbredenberg** [comment]
Connects with issue #123 

The meeting 15th of November suggest changing "CAN" to "MUST" so there are a METS document for the representation created and placed in the representations.
