### ISSUE TITLE
CSIPSTR11 & CSIPSTR13: don't agree with MoSCoW classification

### ISSUE THREAD

**Issue by hsilva-keep** [DILCISBoard/E-ARK-CSIP#180]
https://carlwilson.github.io/E-ARK-CSIP/specification/implementation/structure/folders/

*CSIPSTR11: The representation folder MUST include a sub-folder named data which includes all data constituting the representation ;*
*CSIPSTR13: The representation folder CAN include a sub-folder named metadata which CAN include all metadata about the specific representation*

Why *data* is mandatory & *metadata* is optional? Using SIP Update as an example (partial updates), we can have two scenarios regarding representations, where one of the folders will have no content:

1. Updating a specific representation metadata file (e.g. descriptive metadata)
2. Updating a specific representation file

IMHO, either we make both mandatory or both optional.

**Comment by PhillipTommerholt** [comment]
I think CSIPSTR13 is related to CSIPSTR5: The Information Package folder MUST include a folder named metadata, which MUST include at least all metadata relevant for the whole package

So in that sense a metadata and a data folder must be present. But it is tricky that we have two layers which leaves the question: where to put what?

I like the idea about SIP updates and IP deltas in general, but so far I guess they are not a part of the IP specs?

**Comment by hsilva-keep** [comment]
@PhillipTommerholt I've just mentioned the SIP Update because its a real use case. But, in the end of the day, the question we need to answer is: why one is mandatory and the other optional?

**Comment by kuldaraas** [comment]
The point was that a CS IP package must have data split into representation folders but, at the same time, implementers might choose to keep all metadata in the root metadata folder. As such it's a must req for rep data and can for rep metadata. 

There were quite a few reasons for this decision. One being that splitting metadata to root and representation might be intellectually challenging, another that for simple "two pdf file" IPs there is no practical need for splitting metadata into representations (esp in the case of a SIP or DIP). 

My opinion is that the req's in CS IP should stay as is, but we might review whether the AIP spec should be stricter here?

**Comment by hsilva-keep** [comment]
@kuldaraas First of all, I'm questioning why one is mandatory & the other is optional, as use cases to support using one and not the other exists for both. And this is merely a technical matter. 

Second, for example, an SIP or AIP can exist and not contain any data at all as they can simply contain metadata (SIP Update or AIP with a representation with metadata describing physical content).

Based on this, I would say that both data & metadata for representations CAN include a sub-folder.

**Comment by karinbredenberg** [comment]
Rewording of the principles has been made.
