### ISSUE TITLE
Illustrations in CS IP/SIP/AIP/DIP

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#185]
All images needs to be checked over and perhaps redrawn so they have the same style and uses the same color scheme.

Ready by month 11!

**Comment by karinbredenberg** [comment]
#117 is part of this task

**Comment by karinbredenberg** [comment]
CSIP image 11 and 12 and the one in chapter 6.2.5 is missing. @DrJaime

**Comment by PhillipTommerholt** [comment]
I have uploaded a .png illustration for image 11 on the g-drive which is slightly improved. It is not the same color scheme though.
