### ISSUE TITLE
Namespaces in examples mets Root

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#194]
I am not an expert, but there might be missing information and a need for extra examples in:

https://github.com/DILCISBoard/E-ARK-CSIP/blob/master/specification/implementation/metadata/mets/mets-root/examples.md 

1. There are no namespaces in the root-element (only xsi:schemalocations)
2. There is no example of a METS.xml at root IP level - only 3 examples at representation level

(This might be on its way - but I am creating an minimal IP with associated schemas and it would have been nice to just copy from the examples )

**Comment by karinbredenberg** [comment]
The examples in full are in the appendixes in the profile. If you look in the profile document they are at the bottom in the element appendix.

**Comment by karinbredenberg** [comment]
Does namespaces and things get lost in the transformation to examples in the text?

**Comment by koit** [comment]
It seems the examples in CSIP core text are not autocreated from the profile XML (or were created from an earlier version). At least the [examples.md](https://github.com/DILCISBoard/E-ARK-CSIP/blob/rel/v2.0-draft/specification/implementation/metadata/mets/mets-root/examples.md) of `v2.0-draft` branch doesn't match the examples of the [profile CSIP.xml](https://github.com/DILCISBoard/E-ARK-CSIP/blob/rel/v2.0-draft/profile/CSIP.xml) of the same branch (both the content and the title of the examples differ).

Also, the profile only has definitions of `metsRootElementExample2` and `metsRootElementExample3`, but CSIP1 to CSIP6 definitions in the profile also refer to `metsRootElementExample1`:

```xml
<requirement ID="CSIP1" REQLEVEL="MUST" EXAMPLES="metsRootElementExample1 metsRootElementExample2 metsRootElementExample3">
```

**Comment by karinbredenberg** [comment]
Example ID's fixed.
