### ISSUE TITLE
Congruency in METS-tables for metsHdr and fileSec ?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#221]
As I understand METS both metsHdr and fileSec are optional.

If I look at http://earkcsip.dilcis.eu/specification/implementation/metadata/mets/filesec/ the table and CSIP58 makes it clear for me that fileSec is optional in METS and that it should be thereaccording to CSIP. 

If I look at http://earkcsip.dilcis.eu/specification/implementation/metadata/mets/metshdr/ then there isn't the same logic. The text above the table indicates that there should be a similar requirement as CSIP58 to state that a metsHdr-element should or must be there - but there isn't one.

**Comment by karinbredenberg** [comment]
Have to wait until after the review.
