### ISSUE TITLE
CSIP82 - @label lower camel case for structMap

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#222]
I know this might be too detailed (please say so if I am not reporting issues in the best possible way).
In CSIP82 we require a label value “CS IP StructMap” which also corresponds to the vocabulary in http://earkcsip.dilcis.eu/schema/DILCISVocabulariesIP.xml 
I think we should use lower camel case for the value (both in the specification and in the vocabulary) to align with the METS way.

**Comment by karinbredenberg** [comment]
There are so many opinions on how to do value lists. Lets wait for comments from the review before we make a decision sine its a lot of values to change.

**Comment by shsdev** [comment]
As this is kind of a variable name, it is good practice to agree on one format and not to mix it. The vocabulary should therefore be adapted, i.e. always start the camel case variable in lower case, no white spaces, etc.
BTW, I think it would be good to use some standard for the vocabulary, such as SKOS, for example.

**Comment by karinbredenberg** [comment]
The vocabulary currently is in a simple schema following how the in EAD3 used iso-lists are looking. Do we need to move it to SKOS? Feel free to do so. (Needs adoption in the transformation of the CS IP document.)
The value lists are value lists, they are not variable names, the variable names are our added attributes and they follow the naming in METS with upper case only and are found in our extension schema.
So can we have values being nore than one word in the value list being separate words or do we need to make them all without spaces?

**Comment by koit** [comment]
This got solved to the value `CSIP structMap` with PR #411.

**Comment by carlwilson** [comment]
Closing, noted a follow on action in #316
