### ISSUE TITLE
Referenced PREMIS files or embedded PREMIS data in METS/amdSec

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#227]
In http://earkcsip.dilcis.eu/#54-use-of-premis it states:

> The two high level requirements for use of PREMIS in Common Specification IPs are that:
-All preservation metadata is created according to official PREMIS guidelines ;
-All PREMIS metadata **is either embedded in or referenced** from the amdSec/digiprovMD element of the appropriate METS file.

In http://earkcsip.dilcis.eu/#534-use-of-the-mets-administrative-metadata-section-element-amdsec it states:

> CSIP is only using referencing of files containing administrative metadata.

I guess there should be some alignment here.

**Comment by karinbredenberg** [comment]
The alignment needed is to remove the inclusion part.

**Comment by carlwilson** [comment]
Closed by #395
