### ISSUE TITLE
The specification allows IPs with no namespace / schema information in the mets root element

### ISSUE THREAD

**Issue by carlwilson** [DILCISBoard/E-ARK-CSIP#228]
As far as I can see we don't prescribe that the submitted METS document declares it's namespace and schema information in the root element, i.e.:

```xml
<mets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns="http://www.loc.gov/METS/" 
  xmlns:csip="https://DILCIS.eu/XML/METS/CSIPExtensionMETS"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance schemas/XMLSchema.xsd http://www.loc.gov/METS/ schemas/mets.xsd http://www.w3.org/1999/xlink schemas/xlink.xsd https://DILCIS.eu/XML/METS/CSIPExtensionMETS schemas/CSIPExtensionMETS.xsd" 
```

This could be a default namespace or add a `mets:` prefix, but I'm not sure that matters but we should insist on the schema information been present.

**Comment by hsilva-keep** [comment]
For clarity reasons, and if no more reasons arise, I would leave it without prefix as it makes reading much easier.

**Comment by carlwilson** [comment]
@hsilva-keep I'm inclined to agree but that's only a point of view, see #143

**Comment by karinbredenberg** [comment]
As in #143 I'm still for always having namespace prefixes since we also add our own prefix for the extra attributes we add. 
A rule to be added in the profile as well as in the text when the review is over.
(It has been in the profile as a question but never got comments so it was removed.)

**Comment by koit** [comment]
It is a subjective issue and it would be good to have some sort of survey of the users of CSIP.

My preference is default namespace without a prefix. I feel the ubiquitous prefixes create visual clutter that drains the attention. In most XML documents (incl. CSIP METS.xml), one namespace dominates overwhelmingly, so having only non-default namespaces prefixed makes them easier to spot, thus less mistakes.

Another issue with prefixing the default is that attribute names of the default namespace are typically still written without prefixes, which causes some confusion on its own (i.e. if everything is supposed to be prefixed, then where do these naked attributes belong):
```xml
<mets:div ID="ID100" LABEL="minimal_IP_with_1_representation">
  <mets:div ID="ID100-1" LABEL="Metadata" />
  <mets:div ID="ID100-2" LABEL="Representations">
    <mets:div ID="ID100-2-1" LABEL="rep1">
      <mets:mptr xlink:type="simple" xlink:href="file:representations/rep1/METS.xml" LOCTYPE="URL"/>
      <mets:div LABEL="data"/>
    </mets:div>
  </mets:div>
</mets:div>
```

The use of non-prefixed default namespace is so broad that people must used to it, so I think we don't have to worry about it.

As to Carl's original comment about not prescribing namespace declaration - it is actually prescribed in the intro text of Chapter 5.3.1. I have proposed moving it into a named requirement, see #408.
