### ISSUE TITLE
Use the same acronym for Common Specification for Information Packages

### ISSUE THREAD

**Issue by hsilva-keep** [DILCISBoard/E-ARK-CSIP#229]
Throughout the document, both **CS IP** (48 times) and **CSIP** (401) are used. 
And we should only use one of the forms, for coherence purposes.

**Comment by hsilva-keep** [comment]
It even happens in the same sentence :)

E.g. **5.3.6. Use of the METS structural map (element structMap)**
`
The structMap element has a mandatory attribute @LABEL which has the fixed value of “CSIP StructMap”. The @LABEL attribute is used to distinguish the Common Specification mandated structural map occurrence from any other, user-defined, structural maps. As such we can also derive the requirement, that any user-defined structural maps must not use the LABEL value of “CS IP StructMap”;
`

**Comment by jmaferreira** [comment]
I support @PhillipTommerholt.

**Comment by karinbredenberg** [comment]
Can we agree upon:
No space in the value of the requirement?
A space when we talk about it as the Common Specification for Information Packages?
a fix that will be implemented after the review, and means going through all the documents!

**Comment by hsilva-keep** [comment]
@karinbredenberg If we take @PhillipTommerholt comment into consideration then I think the right way would be to add an hyphen (or any other char to divide *CS* from *IP*), something like **CS-IP12**.

**Comment by karinbredenberg** [comment]
Rember that the ID's are true xml:id's.

**Comment by hsilva-keep** [comment]
@karinbredenberg indeed, your right ;)

**Comment by jmaferreira** [comment]
Options:

* CSIP12
* CS-IP12
* CS.IP12

**Comment by karinbredenberg** [comment]
I would keep it as it is in the ID's since we need to redo also in the validation if we change.

**Comment by koit** [comment]
I discovered that I had posted this problem as #410.

**Comment by carlwilson** [comment]
All gone now.
