### ISSUE TITLE
Is there any particular logic for the order of authors in the spec?

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#230]
For example, Alex appears halfway through the table and he has not participated in version 2.0.0.

I suggest alphabetical order.

**Comment by karinbredenberg** [comment]
It has just been lifted from the old document as it is. Perhaps two lists, one with previous participants in the work and one with current contributors? And yes preferably alphabetical.

**Comment by jmaferreira** [comment]
I agree.

**Comment by carlwilson** [comment]
To fix this we need to decide where the authors go, and ensure that PDF and site publication support the solution. Suggestion, Appendix for author and history information? Just changes in latest version as forward material.

**Comment by karinbredenberg** [comment]
See this issue: https://github.com/DILCISBoard/GroupDocumentation/issues/17
