### ISSUE TITLE
The Introduction section on the CSIP is not really an introduction

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#231]
The opening text of the introduction does not provide a good starting point for a newcomer. I suggest setting the stage with a description of OAIS, Packages and then the purpose of this specification set.

All the text necessary is already available on the sub-sections. I'm just recommending a restructure of the contents of the Introduction section.

See: http://earkcsip.dilcis.eu/#1-introduction

**Comment by carlwilson** [comment]
So we shouldn't repeat text from other specifications but a short introduction that adds some beginners level context might be useful, even if it's just a primer reading list as an appendix.

**Comment by karinbredenberg** [comment]
https://github.com/DILCISBoard/GroupDocumentation/issues/17

**Comment by karinbredenberg** [comment]
Common introduction made and gets added in the transformations.
