### ISSUE TITLE
Section 1.2 mentions the DILCIS Board without any previous introduction to DILCIS

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#236]
This goes in line with my comment #231 about the poor structuring of the introduction section. Key concepts are not being well introduced to the reader.

Maybe @DrJaime  can review this entire section to make it clear to the unexperienced reader.

**Comment by DrJaime** [comment]
Hi Miguel,

This certainly can be looked at but at present the CS IP text is in a state
of limbo. We can do changes but not make approved PR's until after we have
seen what the review comments are.

Best wishes,


Jaime

**Comment by karinbredenberg** [comment]
Common introduction made and gets added in the transformations.
