### ISSUE TITLE
The acknowledgements section is still very much focused on EARK. Needs deep revision

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#237]
It addresses the spec as a "deliverable" and not a proper spec.

We should use this section to include proper acknowledgements to whoever participated in this version of the spec. A "history" section could be added to explain the story behind the specs:

1. E-ARK
2. DILCIS
3. E-ARK4ALL/eArchiving

**Comment by karinbredenberg** [comment]
Ties into #231 
A first version of new introduction is here: https://github.com/DILCISBoard/GroupDocumentation/issues/17

**Comment by karinbredenberg** [comment]
Common introduction made and gets added in the transformations.
