### ISSUE TITLE
Principle 3.1: No mention of Representation Information

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#243]
We need to start looking into "Representation Information" as being part of the CSIP. This shall not be regarded as "metadata" but more as "information" necessary to understand the data.

I'm not suggesting addressing this issue in this version of the spec, but we definitely need to address this in the near future. The AIP spec already has a section about this (as far as I can remember). However, this should be part of the CSIP, as it makes total sense in the SIP and the DIP as well.

I can provide examples on how this is important, but I'll leave those for a meeting.

**Comment by karinbredenberg** [comment]
Is added as example in CSIPSTR16. #252

**Comment by carlwilson** [comment]
I agree that Representation Information should at least be mentioned in the document. I believe that it's still metadata, just a particular class/collection of metadata. PREMIS does have the capability to deal with rep information (I believe), certainly finding a standard way of handling it and recommending is the best way forward. @carlwilson to look at PREMIS quickly, but we're looking to add a mention and a hook for future detail, not solve the issue.

**Comment by karinbredenberg** [comment]
Can the remake of the textual update in CSIPSTR16 ( #632 ) be the solution @carlwilson ?

**Comment by karinbredenberg** [comment]
Closed with PR #680
