### ISSUE TITLE
CSIPSTR3: Should we be more prescriptive about which compression algorithms shall be supported

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#249]
This could be a MAJOR interoperability issue. If I deliver packages to an archive in ARJ format (a popular compression format in the 90s), how many will be able to process this?

SIARD 2 spec is also very prescriptive about the compression algorithms to use. We should be as well.

**Comment by karinbredenberg** [comment]
Lets see what comes from the review.

**Comment by carlwilson** [comment]
We may want to clarify use of archive/compressed formats and perhaps make recommendations based on these thoughts.
