### ISSUE TITLE
CSIPSTR16: There is no mention of Representation Information. We should add this to the examples.

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#252]
The notion of "documentation" is not OAIS. There is no harm in using "documentation" but we should also  make a reference to "Representation Information".

**Comment by karinbredenberg** [comment]
@carlwilson just add the term in CISPSTR16?

**Comment by carlwilson** [comment]
The term "supplementary documentation" is pretty loose but Representation Info is just an example. Give a few examples of "supp doc" and RI should be an example.

**Comment by karinbredenberg** [comment]
Examples added.
