### ISSUE TITLE
Section 5.2: The use of identifiers

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#253]
The text says:

> To overcome this limitation and allow for interoperable package identification all identifiers within Common Specification metadata MUST start with a prefix, followed by the value of the identifier.

Why does it MUST start with a prefix? Imagine my repository has a ALL LETTERS numbering/identification scheme. Why should I have to prefix it?! This makes no sense to me. 

This is a limitation of the UUID identification scheme. Other identification schemes may not have this limitation. I suggest removing the MUST and just call it a recommendation for certain types of identifiers, e.g. the UUID.

**Comment by karinbredenberg** [comment]
The UUID can start with a number and thats one problem with the xml:ID which cant start with a number.

**Comment by jmaferreira** [comment]
I know that. But that's a restriction of the UUID not ALL identifiers. The requirement should be... the identifiers should conform to XML:ID.

**Comment by karinbredenberg** [comment]
Dont miss the problem of people not understanding xml:ID even if we give the rules for it......

**Comment by carlwilson** [comment]
Clarify requirement for xml:id type, make the requirement identifiable (it's not currently) and refer to that.
