### ISSUE TITLE
Examples need more context

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#256]
I struggled to understand the following examples in the text. We need a bit a context before introducing them in the document:

* Example: METS root element example with content not in the value list being transfered
* Example: METS root element example of content with a type from the value list and representation content not in the value list

**Comment by karinbredenberg** [comment]
They are coming directly from the profile so if more text is needed it needs to be as comments in the text, no elements available in the METS profile example element.

**Comment by koit** [comment]
I agree we have a problem and I would consider it as two separate issues:

1. The labels of examples (i.e. profile CSIP.xml attribute `Example/@LABEL`) need rewording. The ones for METS root that Miguel brought up are perfect examples of this: I can't understand the current wording. Is it that the first one is meant to be for an IP that contains only metadata and the other one for an IP with some payload in the representations folder? I think the label should state the purpose of the IP, such as "METS root element for an IP that contains only metadata."
2. We need to describe the parts of the IP that surround the example, as the METS XML is only meaningful as part of an IP with folders and files, e.g. metsRootElementExample2 might have such explanation:

"This example assumes the IP has the following folder and file structure:

```
uuid-4422c185-5407-4918-83b1-7abfa77de182/
                                         |- METS.xml
                                         |- metadata/
                                         |- representations/
                                                           |- rep1/
                                                                  |- data/
                                                                         |- document.txt
```

The XML exerpt in the example is from the METS.xml in the root folder of the package."

Regarding impementation of issue 2, one option is XML comments inside the example text, but this is not user friendly as it doesn't allow formatting. I think it would be better to use examples.md but I assume these are autogenerated from CSIP.xml - @carlwilson, can you come up with some magic to do it?

**Comment by koit** [comment]
One more thing: ideally, the exerpts should be from the same IP, so the reader could incrementally construct the whole IP in their imagination. We could consistently use two examples: one for the simplest possible case and the other one more complicated. The exerpt after each section would be taken from the full examples, which would be presented as Appendix 1 and 2.

That way, instead of having context explanations before each example, we could have a section titled "About the examples" placed in the beginning, as 5.2.1 or 5.3.1.

**Comment by karinbredenberg** [comment]
The example label text has been updated.
