### ISSUE TITLE
CSIP62 & CSIP63: why???

### ISSUE THREAD

**Issue by hsilva-keep** [DILCISBoard/E-ARK-CSIP#268]
We already have the attributes **CONTENTINFORMATIONTYPE** & **OTHERCONTENTINFORMATIONTYPE** in the mets element, therefore available for both root & representation METS.xml, i.e. to describe the content of the package as a whole or the content of a certain representation. 
So, why do we need them in a fileGrp?

**Comment by karinbredenberg** [comment]
Since you can have a mixed package they are used in the filegrp to describe there what it is.

**Comment by karinbredenberg** [comment]
@hsilva-keep is this clear and can it be closed?

**Comment by koit** [comment]
@karinbredenberg, is the idea that in case of a package that contains both ERMS and SIARD2 data, there would be:
- `mets/@csip:CONTENTINFORMATIONTYPE` = `MIXED`
- one fileGrp with `fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE` = `ERMS`
- another fileGrp with `fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE` = `SIARD2`
