### ISSUE TITLE
CSIP64: 'whole folder structure'?

### ISSUE THREAD

**Issue by hsilva-keep** [DILCISBoard/E-ARK-CSIP#269]
In the previous version (see page 39 of the version 1.0 of the document), the `USE` attribute of a certain fileGrp was the name of the folder, this way and with the nesting done using several fileGrp one can see the 'whole folder structure' that set of files belong to.
Why have this been changed?

Also, we should use lower case in the examples and, even if they are examples, use only the values needed by the CS IP.

**Comment by karinbredenberg** [comment]
Goes back to the structMap discussion we had.

**Comment by carlwilson** [comment]
Resolve with reference to #366 #367 #369

**Comment by karinbredenberg** [comment]
No nesting of file groups in this version.

**Comment by karinbredenberg** [comment]
Check of consisty of names of folders needed, in vocabs as well as examples.
