### ISSUE TITLE
CSIP1 OBJID - Improve description

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#270]
**CSIP1 - "Content Identification" `mets/@OBJID` has issues that can be improved.**

The current [description](http://earkcsip.dilcis.eu#CSIP1) reads:
>It is mandatory to use a content ID which is expressed with @OBJID. The value should be the same as the name or ID of the package (the name of the root folder) for the root METS document or the name and folder name for the representation. The OBJID must meet the principle of being unique at least across the repository.

### Issue 1

>The value should be the same as the name or ID of the package (the name of the root folder) for the root METS document or the name and folder name for the representation.

The wording is somewhat unclear. I propose:
>For the METS document in the root folder, @OBJID should be equal to the package ID (i.e. the name of the root folder, see [CSIPSTR2](http://earkcsip.dilcis.eu#CSIPSTR2)). For a METS document in a representation folder, @OBJID should be equal to the representation ID (i.e. the name of the representation folder, see [CSIPSTR10](http://earkcsip.dilcis.eu#CSIPSTR10)).

Note that the nature of this requirement is more about structure than about XML, so it seems logical to move it to a separate structural requirement CSIPSTRXXX, but that would add more complexity to the topic that is already scattered across [Principle 2.5](http://earkcsip.dilcis.eu/#principle-25), [CSIP1](http://earkcsip.dilcis.eu#CSIP1), [CSIPSTR2](http://earkcsip.dilcis.eu#CSIPSTR2) and [CSIPSTR10](http://earkcsip.dilcis.eu#CSIPSTR10).

### Issue 2

>The OBJID must meet the principle of being unique at least across the repository.

This is almost impossible to test with a package validator and should be moved to best practice guidelines, so there should be something like GUIDELINEXXX that reads:
>The information package ID (and thus the name of the root folder and the value of mets/@OBJID attribute) must be unique at least across the repository.

### 1. CSIP1

Change the description of CSIP1 to:
>@OBJID must be used for identifying the METS document (see [Principle 2.5](http://earkcsip.dilcis.eu/#principle-25)). For the METS document in the root folder, @OBJID should be equal to the package ID (i.e. the name of the root folder, see [CSIPSTR2](http://earkcsip.dilcis.eu#CSIPSTR2)). For a METS document in a representation folder, @OBJID should be equal to the representation ID (i.e. the name of the representation folder, see [CSIPSTR10](http://earkcsip.dilcis.eu#CSIPSTR10)).

### 2. GUIDELINEXXX

Add a best practice guideline GUIDELINEXXX that reads:
>The information package ID (and thus the name of the root folder and the value of mets/@OBJID attribute) must be unique at least across the repository.

**Comment by koit** [comment]
I made the mistake of assuming that `mets/@OBJID` has to be of type `xsd:ID`, so to spare others from the same mistake, I propose adding a comment to the end of the description of CSIP1:

>Note that `mets/@OBJID` is of type `xsd:string`. METS defines another attribute `mets/@ID`, which is of type `xsd:ID`, but this attribute is optional in CSIP.

**Comment by carlwilson** [comment]
Fixed by #462
