### ISSUE TITLE
Possible CSIP17 and CSIP92 inconsistency

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#272]
http://earkcsip.dilcis.eu/#CSIP17 has cardinality 0..n
http://earkcsip.dilcis.eu/#CSIP92 has cardinality 0..1

CSIP92 must have cardinality 'n' to be consistent with CSIP17.
Otherwise it is not possible to link from the structMap to the more than one dmdSec - and we allow many dmdSec - if one would like to do so.
The use of cardinality '0' and level 'MUST' does not make it easier to understand.
How do we interpret cardinality 0 and level 'MUST' for CSIP92?

Found during A3 validation @DILCISBoard/a3-validation 

(At the DNA @PhillipTommerholt  we assume less than 10 files for descriptive metadata to be used, so having to link to 10 dmdSec ID is not a problem).

**Comment by karinbredenberg** [comment]
Its an attribute, in the attribute you add all the DMDID's as described in the text. We cant make it a 0..n since its an attribute.
We can chnage the MUST after the review, but 0..1 remains.

**Comment by PhillipTommerholt** [comment]
The problem seems to be that the MoSCoW and the cardinality can be expressed for many different aspects. I guess what we want to say is:

> If there exists descriptive metadata in the IP (and therefore 1..n dmdSec elements with dmdSec/@IDs), then there MUST be 1 DMDID-attribute which references all the dmdSec/@IDs. If there are more than one dmdSec/@ID, then the IDs must be separated with one SPACE character. 

Something like that?

**Comment by carlwilson** [comment]
We need some wording to account for conditional cardinality i.e. if "x" then "y" is required else no "y" is OK.
