### ISSUE TITLE
Possible invalid XML in example

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#273]
The example after
http://earkcsip.dilcis.eu/#533-use-of-the-mets-descriptive-metadata-section-element-dmdsec
does not seem to validate.
The attribute `mimetype` must be in uppercase MIMETYPE

Example: METS example of referencing descriptive metadata in the for of an EAD document
```xml
<mets:dmdSec ID="uuid-906F4F12-BA52-4779-AE2C-178F9206111F" CREATED="2018-04-24T14:37:49.609+01:00">
  <mets:mdRef LOCTYPE="URL" MDTYPE="EAD" type="simple" href="metadata/descriptive/ead2002.xml" mimetype="application/xml" SIZE="903" CREATED="2018-04-24T14:37:49.609+01:00" CHECKSUM="F24263BF09994749F335E1664DCE0086DB6DCA323FDB6996938BCD28EA9E8153" CHECKSUMTYPE="SHA-256">
  </mets:mdRef>
</mets:dmdSec>
```

**Comment by karinbredenberg** [comment]
Will be fixed in the release after review at least. also see that the example lacks xlink: on type and href, so that also needs to be investigated. Guess it happens in the transformation.

**Comment by karinbredenberg** [comment]
attribute name fixed.

**Comment by karinbredenberg** [comment]
XLink is in issue #337
