### ISSUE TITLE
The principles

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#278]
Are   principles the baseline of the CSIP design? Or guidelines for implementers of   the CSIP? Statements like “It MUST be possible to include any data or metadata in a Information   Package regardless of its type or format.” look   more like a principle for CSIP design, while “Any   Information Package MUST   have an identifier which is unique and persistent within the repository.” looks like it’s a recommendation for an implementer (making   an identifier persistent is completely up to the implementer’s commitment,   E-ARK specifications cannot guarantee anything about the identifiers’   lifecycle.)

Related to section: I, 3
Text comment relates to: This is also the goal of this Section, which presents a series of high level principles to guide the technical details delivered in Part II of this specification.

**Comment by carlwilson** [comment]
This needs a little thought. I agree (in principle ;) ) with this as design principles shouldn't talk about repository implementations. Look at wording for principle 2.3 - 2.5

**Comment by karinbredenberg** [comment]
Not sure how to change the wording here @carlwilson

**Comment by carlwilson** [comment]
Believe this is now stale and the guidelines have moved on significantly.
