### ISSUE TITLE
Using E-ARK tools in principe 4.1

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#282]
Does it mean we can use E-ARK tools without using METS/PREMIS ?

Section: I, 3.4, principle 4,1
Text: In the current implementation a large proportion of such metadata is covered by the widely used METS and PREMIS standards (see Section 5).

**Comment by carlwilson** [comment]
E-ARK tools are based on the METS and PREMIS implementations and require METS files for packages and representations,
