### ISSUE TITLE
Section II, 4 meaning of import/export

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#286]
The meaning of "import/export"  needs to be explained can be thought as an alternative way to create SIPs and DIPs. To clarify this, wording lie this might aid "conversion from/to internal AIPs"

Section: II, 4
Text: import/export of AIPs

**Comment by carlwilson** [comment]
Talk to Sven and Kuldar as to what's the difference between a "transfer AIP" and a SIP. If we can clarify the difference and the use case behind the difference we can improve the text.

**Comment by karinbredenberg** [comment]
Mail sent to Sven asking for comments.

**Comment by shsdev** [comment]
In the following, I will express my opinion, please feel free to disagree:
The purpose of the DIP is to provide access according to requirements for rendering the data in a specific environment. Usually, it only includes the data required for rendering the IP, and, in particular, it does not need to contain the master data (making the DIP unnecessarily large in many cases). To use the DIP for exporting IPs is a workaround where existing package creation functionality is re-used for the purpose of persisting the current state of an IP. However, the DIP was not conceived with this porpose mind. 
In contrast to the DIP, the AIP provides a meta-structure which allows mapping the full provenance of the IP: the AIP can include the original submission, intermediate changes, and the current state of the IP, and ideally allows reconstructing the current state from 1) the original state, 2) intermedate states, and 3) using the preservation information included. 
An AIP should not need to be "imported". An archival system should be able to read the provenance of the AIP, make the data accessible, allow building new DIPs, and allow creating new SIPs which change the state of the AIP by continuing the line of provenance.
However, in practice we can see the AIP also as an "export format" in the sense that it fully persists the state of an IP (or a series of IPs). 
Regarding the term "transfer AIP", I find this term confusing. The purpose of the IP is to create a "transferable entity". The SIP can be transfered to the archival system, the DIP to the access environment, and the AIP to any storage device: the IP is transferable in itself.
