### ISSUE TITLE
Content of folder metadata, section II, 4.1

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#291]
Does it mean descriptive metadata specific to intellectual components of the IP should not be placed in this folder (e.g., if the IP contains a digital music album, metadata about each track)? Does this mean it's just that metadata specific to a given representation should go to the corresponding metadata folder in each representation folder. This sentence is slightly confusing, maybe something like this instead "descriptive metadata, and preservation metadata relevant to the whole package"?

Section: II, 4.1
Text: The Information Package root folder MUST include a folder named metadata, which SHOULD include metadata relevant to the whole package.

**Comment by carlwilson** [comment]
We need better text explaining the differences between package and representation level and the corresponding use of mets. This may need improvements to CSIPSTR5.

**Comment by karinbredenberg** [comment]
Something more needed in CSIPSTR5, @carlwilson ?

It currently looks like this:
**CSIPSTR5**: The Information Package root folder **SHOULD** include a folder named `metadata`, which SHOULD include metadata relevant to the whole package.
