### ISSUE TITLE
Metadata about components? Section II, 4.1

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#292]
Metadata about components: what are they, if descriptive metadata are inside the metadata folder?

Section: II, 4.1
Text: The Information Package root folder MUST include a metadata file named METS.xml , which MUST include information about the identity and structure of the package and its components at a minimum down to a general description or pointer to each representation.

**Comment by carlwilson** [comment]
Check against ISAD(G) and EAD terminology to avoid ambiguity.

**Comment by karinbredenberg** [comment]
From EAD TL : " @level; component (e.g., subgroup, series, file) Full list (class, collection, file, fonds, item, otherlevel, recordgrp, series, subfonds, subgrp, subseries). " Its also used as in short c as the element for the different levels.
From ISAD(G):  No explanation its used twice, the closest explanationish is: "a unit of description and its
component parts"

**Comment by karinbredenberg** [comment]
Fixed in PR #443
