### ISSUE TITLE
Is subfolders possible? Section II, 4.1

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#293]
In general, is it possible to create intermediary folders? E.g., creating 'master' and 'ocr' folders in a 'data' folder? Or can't 'descriptive', 'preservation' and 'data' folders contain folders? The text remains silent on this point here, but the option of creating subfolders is mentioned below, in the <structMap> section of the document.

**Comment by carlwilson** [comment]
Check against the catalogue / folder structure text: #366 #367 #369

**Comment by karinbredenberg** [comment]
@carlwilson do we need to add some extra text before the folder requriments in the text that its possible to have subfolders just these overall dfolder structure needs to be followed?

**Comment by karinbredenberg** [comment]
Should we add this to the end of the first paragraph, @carlwilson ?

"Additional sub-folders created by the user may be present in the folders described."

**Comment by karinbredenberg** [comment]
CIPSTR14 covers this.
