### ISSUE TITLE
Should and must in section II, 5.3.1

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#300]
If the cardinality is 1..1, it's not SHOULD but MUST.

Section: II, 5.3.1
Text:  1..1 SHOULD

**Comment by carlwilson** [comment]
Group review of cardinality vs. error level. Check against corpus and test case generation rules.

**Comment by carlwilson** [comment]
Change cardinality of CSIP4 to `0..1` and remain a SHOULD.
