### ISSUE TITLE
Change in section II, 5.3.6

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#315]
Change to "Sub structural division structMap/div/div[@LABEL='metadata']" same suggestion for Documentation and Schemas

Section: II, 5.3.6
Text:  Sub structural division structMap/div

**Comment by carlwilson** [comment]
Review granularity / specificity of xPath expressions generally.

**Comment by karinbredenberg** [comment]
XPaths has been added in all places.
