### ISSUE TITLE
Consistency of case in section II, 5.3.6

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#316]
Sometimes the controlled value of folder names starts with an upper-case letter, sometimes with a lower-case letter. Should be unified.

Section: II, 5.3.6
Text: The metadata division (div) element in the package uses the value “Metadata” as the value for the attribute LABEL.

**Comment by koit** [comment]
These are present in:

- CSIPSTR rules 5-11, 13, 15, 16
- CSIP rules 48, 60, 64, 66 etc.
- VocabularyFileGrpAndStructMapDivisionLabel in [DILCISVocabulariesIP.xml](https://github.com/DILCISBoard/E-ARK-CSIP/blob/rel/v2.0-draft/schema/DILCISVocabulariesIP.xml)

**Comment by carlwilson** [comment]
Will be making vocabulary case consistent in a late review sweep, assisted by an automated search with manually curated replace.

**Comment by karinbredenberg** [comment]
This will require a major update in not only the CSIP but also in the validations tools and so on. Its on the agenda for a revsion further on where the change will be all in lower case and spaces are replaced with underscore.
