### ISSUE TITLE
Wanted change in section II, 5.3.6 regarding CONTENTID

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#317]
CONTENTID does not exist as a METS attribute of a <div> section - only CONTENTIDS exists, and this is not a standard way to reference file/fileGrp sections - its value type is "URIs", not "IDREF", which means the XSD schema won't control that the value exists as a valid XML ID in the METS file. Consequently the recommendation is using <fptr FILEID=''"> instead.

Section: II, 5.3.6
Text: Documentation file referencing, structMap/div/div/@CONTENTID

**Comment by carlwilson** [comment]
Missing S in descriptions have been added, review "abuse" of METS standard and consider alternatives.

**Comment by karinbredenberg** [comment]
Change from use of CONTENTIDS to <fptr> will be done.
