### ISSUE TITLE
Refrence vocabulary in section II, 5.3.6

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#318]
Not sure about which vocabulary is referred to here. It would be nice to point to it.

Section: II, 5.3.6
Text: The Library of Congress has developed its own identifier type vocabulary and the CS IP recommends its use

**Comment by carlwilson** [comment]
Proof read document and ensure relevant links are added.

**Comment by karinbredenberg** [comment]
Text changed and made more clear.
