### ISSUE TITLE
Use of techMD

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#320]
The technical metadata should be included in techMD section. Now this section is completely bypassed.

**Comment by carlwilson** [comment]
Review wording guidance on techMD section.

**Comment by carlwilson** [comment]
This issue is a side-effect of the use of PREMIS to record technical metadata. The PREMIS metadata is placed in the digital provenance section. Use of PREMIS is not mandated, the specification should make this point more clearly, and ideally provide an techMD example.
