### ISSUE TITLE
Internal linking and level of the package

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#322]
Internal linkages and level of a packet are somewhat unclear. What is described and where? These should be clarified.

**Comment by carlwilson** [comment]
Look at clarity of wording for representation METS and levels.

**Comment by carlwilson** [comment]
This is impossible to judge as the initial issue description is too loose to make a judgement. Unclear how and what might improve it? In its current state close because it's meaningless.

**Comment by carlwilson** [comment]
This is caused in part by there being no standard way of recording relative internal links, the issue can be closed as a working linkage method is a different issue.
