### ISSUE TITLE
ID's in Chapter 5.2

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#331]
Ch. 5.2: The use of IDs: Quite a lot of explanation, should you just define a fixed prefix?

Section: Ch5.2

**Comment by karinbredenberg** [comment]
Needs to be discussed, revisiting explanation in Chapter 5.2. Connected with issue #332

**Comment by carlwilson** [comment]
The issue here is that it forces users with perfectly good existing prefixes / identifiers to add another prefix on top.
