### ISSUE TITLE
Distinguish direction in Chapter 6.2.2 and 6.2.3

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#340]
Chapters 6.2.2 and 6.2.3: How to distinguish the cases between chapters 6.2.2 and 6.2.3? Is there an attribute, which explains the direction?

Section: Ch 6.2.2 and 6.2.3

**Comment by karinbredenberg** [comment]
I suggest we remove this text for now and work through it and put it back in the next version? @andersbonielsen

**Comment by carlwilson** [comment]
I've talked to @andersbonielsen and this concept is also documented in the AIP. Removing might cause consistency problems. @carlwilson to review today and will propose something for the A2 meeting on 14/05.

**Comment by andersbonielsen** [comment]
See also AIP
https://github.com/DILCISBoard/E-ARK-AIP/blob/master/index.md#child-aip-references-parent-aip
https://github.com/DILCISBoard/E-ARK-AIP/blob/master/index.md#parent-aip-references-child-aips

**Comment by karinbredenberg** [comment]
DILCIS Board meeting at 21st of May decided that this part needs more work involving more partners from DILCIS as well as E-ARK so for now this part will be shortened until a result has been reached.

**Comment by carlwilson** [comment]
Trusting that the rewritten AIP specification handles these issues and closing this
