### ISSUE TITLE
Restricting the standard

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#351]
Since the standard is created to support “interoperable IPs”, and it argues “available and widely used international specifications (most notably METS and PREMIS ) lack the necessary implementation-level detail, needed in order to serve as an authoritative source for practical interoperability”, make a strict standard as possible (without compromising future extensibility).

**Comment by carlwilson** [comment]
We have created an interoperability standard but don't aim to be prescriptive regarding all metadata standards that can be embedded.
