### ISSUE TITLE
Use of PREMIS

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#360]
Use of PREMIS (chapter 5.4, pages 73-74) We welcome the use of PREMIS for preservation metadata. We feel however that the discussion of PREMIS in the Common Specification is too short to adequately allow an unambiguous implementation of the specification.

**Comment by karinbredenberg** [comment]
Connected to overall comment [https://github.com/DILCISBoard/GroupDocumentation/issues/13](https://github.com/DILCISBoard/GroupDocumentation/issues/13)

**Comment by karinbredenberg** [comment]
More PREMIS work will be carried out.

**Comment by carlwilson** [comment]
PREMIS is now been handled in https://citspremis.dilcis.eu/
