### ISSUE TITLE
Proposal of adding Retention/Disposal element nr 1

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#361]
Proposed element Preservation status. 

Element: Status for retention, disposal or preservation. 
Element type: String. 
Allowed values: S, DI, PA, UN (S=Save, preserve, DI=Disposal, retention, PA=Paused, UN=UNknown)

**Comment by karinbredenberg** [comment]
Connected with #362 and #363

**Comment by karinbredenberg** [comment]
A convention for how to add this kind of information in for example amdSec using an existing standard in an implementer guide line is needed. This might be a local implementation of the CSIP.

**Comment by carlwilson** [comment]
This can be done locally if required but is beyond the scope of a generally applicable specification.
