### ISSUE TITLE
Proposal of adding Retention/Disposal element nr 2

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#362]
Proposed element Preservation date.  Dependent on value of #361 

Date after which disposal of AIP shall occur if PreservationStatus="DI". That is preservation shall only occur up to and including this date, i.e. package shall be retained to this date. E.g. ”2020-01-01” means that the AIP shall be destroyed (directly) after this date (or retained to this date depending on ones viewpoint.). Element type: YYYY-MM-DD. 
Dependence: Shall be given if PreservationStatus="DI". Otherwise it is optional.

**Comment by karinbredenberg** [comment]
Connected with #362 and #363

**Comment by karinbredenberg** [comment]
A convention for how to add this kind of information in for example amdSec using an existing standard in an implementer guide line is needed. This might be a local implementation of the CSIP.

**Comment by carlwilson** [comment]
This can be done locally if required but is beyond the scope of a generally applicable specification.

**Comment by shsdev** [comment]
I would propose adding retention/disposal elements to the AIP. See https://github.com/DILCISBoard/E-ARK-AIP/issues/35
