### ISSUE TITLE
Proposal of adding Retention/Disposal element nr3

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#363]
Proposed element Preservation reference. Law or other regulation that determines preservation, disposal or retention. E.g. "RA-FS 2030:12". 

Element type: Free text. 
ConditionMin 1 character. Max 255 characters

**Comment by karinbredenberg** [comment]
Connected with #361 and #362

**Comment by karinbredenberg** [comment]
A convention for how to add this kind of information in for example amdSec using an existing standard in an implementer guide line is needed. This might be a local implementation of the CSIP.

**Comment by carlwilson** [comment]
This can be done locally if required but is beyond the scope of a generally applicable specification.
