### ISSUE TITLE
Proposal of adding Information security classification

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#364]
Proposed element Classification. Security classification of information in package.

Elements type: String.
Allowed values: P, BS, HS, EJ KLASSAT. "EJ KLASSAT" is default. Values could be extended to support different organisations requirements.
Values meaning: P=Publik (eng. public or declassified), BS=Begränsat Skyddsvärde (eng. restricted), HS=Högt Skyddsvärde (eng. confidential), EJ KLASSAT=Ej Klassat, okänd klassning (eng. unclassified, unknown).

**Comment by karinbredenberg** [comment]
A convention for how to add this kind of information in for example amdSec using an existing standard in an implementer guide line is needed. This might be a local implementation of the CSIP.

**Comment by carlwilson** [comment]
This can be done locally if required but is beyond the scope of a generally applicable specification.
