### ISSUE TITLE
Proposal of adding Keywords (subjects) to make an IP searchable

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#365]
Proposed element Keywords. A list of keywords used for searching. 
Example: "TMJ, BB, varumärkesintrång, värde2variabel" or "TMJ BB varumärkesintrång värde2variabel". Element type: Free text.
Requirement: Max 20 words separated by (space) or (comma). Max 2047 characters.

**Comment by karinbredenberg** [comment]
A convention for how to add keywords in for example dmdSec in an implementer guide line is needed.

**Comment by carlwilson** [comment]
This can be done locally if required but is beyond the scope of a generally applicable specification. Probably best dealt with as descriptive metadata/finding aids.
