### ISSUE TITLE
Clarification of use of METS

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#368]
The use of METS needs a better explanation. We only see one profile, which must mean that it is the same information in root METS.xml as in representation METS.xml, which becomes confusing when it is stated in the document that the information in root METS.xml and METS.xml should not be on both files. So there is a need for a clearer explanation of what information should be contained in root METS.xml and what information should be in representation METS.xml.

**Comment by carlwilson** [comment]
We need to add definitive rules that describe the policy for nested METS documents. The principle should be that when you have multiple nested METS documents that each document is responsible for the content and metadata below it in the package hierarchy. For example if you have a representation METS document, the parent should only point to that and not to any of the content and metadata in the representation, that's the responsibility of the representation METS file.
