### ISSUE TITLE
Obligation of File Checksum and Checksum type

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#370]
We would like to see that File checksum and File checksum type in FileSec were optional in cases where there is no need to use any checksum when transferring in a controlled environment for example.

**Comment by karinbredenberg** [comment]
This is not a recommended feature. More discussion is needed. Level of conformance? (So there are conformance levels that don't check package integrity?)

**Comment by carlwilson** [comment]
The IP specifications are as much/more about retention than just transmission and this isn't appropriate.
