### ISSUE TITLE
Number of specifications for IP's

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#371]
In Sweden we have not created separate FGSs for SIP, AIP and DIP. We recommend that all extra elements for SIP, AIP and DIP should be included in CSIP, but as optional information. Then, documents are needed that describe how to create a SIP, AIP, DIP and how to use the elements at EU level and that it is possible to adapt for local use in different countries.

**Comment by karinbredenberg** [comment]
More discussions is needed.

**Comment by jmaferreira** [comment]
@karinbredenberg Has there been any decision on this topic? I need a strategic decision in order to implement at the SIP level.

**Comment by karinbredenberg** [comment]
DILCIS Board have decided (17/4-2019) that there will not being a merge of the documents at this point it might be considered in the future. SIP/AIP/DIP might raise things to the CSIP but we don't intend to merge them.
