### ISSUE TITLE
Inconsistency with embedded or linked metadata in CSIP32 and http://earkcsip.dilcis.eu/#534-use-of-the-mets-administrative-metadata-section-element-amdsec

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#380]
DILCISBoard/eark-ip-test-corpus#103
http://earkcsip.dilcis.eu/#CSIP32
The requirement text cites METS and mentions embedded or linked metadata, but according to http://earkcsip.dilcis.eu/#534-use-of-the-mets-administrative-metadata-section-element-amdsec
CSIP is only using referencing of files containing administrative metadata. So embedding is not allowed.

**Comment by carlwilson** [comment]
Discussed with @karinbredenberg, looking at http://earkcsip.dilcis.eu/#53-use-of-mets it's clear that we only recommend using references but don't mandate it. The text will be tightened to remove the ambiguity.
