### ISSUE TITLE
CSIP101

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#381]
CSIP101 says:
![image](https://user-images.githubusercontent.com/15984159/54814912-f7ecbe80-4c90-11e9-8579-cdc97d9bf8e0.png)

I do not understand the sentence. It is my understanding that you can not have data in a CS IP that is not in a representation?

**Comment by carlwilson** [comment]
Applies to a metadata update package I believe?

**Comment by carlwilson** [comment]
This requirement refers to metadata only packages. The problem appears to be that some content element is required in the METS struct map, it's the only mandatory element. The empty content representation is used for this.
