### ISSUE TITLE
Testability of @xlink:href attribute in METS 

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#398]
Might be related to https://github.com/DILCISBoard/E-ARK-CSIP/issues/306 

There are requirements about the @xlink:href attribute in CSIP24, CSIP38, CSIP51, CSIP79, and CSIP110.

The descriptions state:

> The actual location of the resource. We recommend recording a URL type filepath within this attribute.

or 
> The actual location of the resource. This specification recommends recording a URL type filepath within this attribute.

When creating testcases for this in A3 we are running in to trouble. The attribute MUST be there and that is easy to check. The value is hard to validate though, if there is no specific details on what we mean by a URL type filepath.

**Comment by karinbredenberg** [comment]
No standard exist for how to give a relative file path. What do exist is this specification [https://tools.ietf.org/html/rfc8089](url)

**Comment by carlwilson** [comment]
We do have an implicit test for these references and a clear rule. They must be legal paths relative to some directory in the package (this is slightly clouded pending resolution of #406). The implicit test is that we check the integrity of a package and we should be able to find said file, and checksum it.

**Comment by carlwilson** [comment]
The last comment still stands. Bumping path resolution to package integrity checking makes these problems go away.
