### ISSUE TITLE
Reformulation of CSIP66 and possible restructuring in fileSec requirements?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#403]
CS IP states:

CSIP66 | File `fileSec/fileGrp/file` | The lowest level file group (fileGrp) contains the file elements which describe the transferred file objects. When the file element is categorised as "Representations" each representation file group contains one file which is the reference to the METS document describing the representation  | 1..1 MUST
-- | -- | -- | --

I suggest we might reformulate to: 

CSIP66 | File` fileSec/fileGrp/file` | The lowest level file group (fileGrp) contains the file elements which describe the file objects in the file group.   | 1..n MUST
-- | -- | -- | --

3 changes in the reformulation:
1.  Change from _**the transferred file objects**_  to  _**file objects in the file group**_
Discussion: I don't think the word 'transferred file objects' is the best word to describe the file object in any given file group. 
2. Removal of _**When the file element is categorised as "Representations" each representation file group contains one file which is the reference to the METS document describing the representation**_
Discussion: I guess what we are trying to say here is something like: 
_"When there is representation data in the IP, then the root METS.xml SHOULD have a a file group where the USE-attribute has the value "Representations".  The file elements within this file group SHOULD describe and point to the METS.xml document in each representation and only to the representation METS.xml(s). In a representation METS.xml, then the the USE-attribute has the value "data" to describe the data files of the representation "_  I don't think that CSIP66 is the best place to describe this complex requirement. I think we might need a visualization and not a table description to solve this. I also the that we need to include "data" as a USE-attribute value in order to distinguish between representations and data files within representation. And also a better description of CSIP64 and the USE-attribute.   
3. Change from _**1..1 MUST**_ to  _**1..n MUST**_
Discussion: file elements can appear multiple times within a file group.

**Comment by karinbredenberg** [comment]
The thought here is that if its a representation the reference is to the METS document is made. So some reformulation is needed it needs to be present in the METS Profile (where we get this text from) the METS profile itself dont display images.
True the cardinality is wrong and should be 1..n
