### ISSUE TITLE
CSIP60 and CSIP64

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#404]
Regardles of the outcome of the [catalogue discussion](https://github.com/DILCISBoard/E-ARK-CSIP/issues/347) CSIP60 and CSIP64 seem redundant.

In CSIP60 it is not mentioned that it is via the  @USE attribute that the  naming (and classification) of the fileGroup takes place and vice versa - it is not mentioned in CSIP64 that this is related to CSIP60? If it is? Or is there something I have misunderstood?

**Comment by karinbredenberg** [comment]
Some clarification in the text is needed then to make it more clear since they aren't redundant. Connection/reference between the requirements have been avoided, not sure we should introduce the cross referencing. It might also be that CSIP60 should be 3..n .

**Comment by karinbredenberg** [comment]
And CSIP60 needs to be splitted. think it all will be more clear then.
