### ISSUE TITLE
xlink:href relative to root IP or representation?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#406]
We have an IP with one representation and a root METS.xml and a representation METS.xml.

In the root METS.xml it makes sense that href's are relative to the root IP, but what about href's in the representation METS.xml? Should they be relative to the IP or the representation?

I think I would prefer that they should also be relative to the IP so that you via the METS.xml can see that this is 1 representation package within an IP.

**Comment by karinbredenberg** [comment]
I think you always reference from "your root" so you can keep the representations somewhere else another hard drive or so and still know what it contains.
