### ISSUE TITLE
Resolve CSIP vs CS IP spelling variation

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#410]
The current version 2.0.0-DRAFT at http://earkcsip.dilcis.eu/ has the following  spelling variations of CSIP:
- `CS IP` 58 instances
- `CSIP` 401 instances

Also, there are 12 instances of `CS IP Information Package`, which can be misread as "common specification information package information package."

I propose unifying the spelling to `CSIP`.

**Comment by karinbredenberg** [comment]
There are other issues regarding this.

**Comment by carlwilson** [comment]
Will be picked up in a semi-automated consistency check once PRs and review issues dealt with.

**Comment by koit** [comment]
The same problem had been posted earlier as #229.

**Comment by carlwilson** [comment]
Fixed.
