### ISSUE TITLE
CSIP109 METS pointer

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#412]
In the A3 group we discussed the CSIP109 requirement.
We think that it need to be reformulated since CSIP states that:
> The structural map in the representations METS file use the structural map the same way with no exceptions

The CSIP109 is formulated as if it is a root METS with representation(s). 

Also - what is the link to CSIP60 and CSIP64? We now have to places in the METS where there is a link/pointer to the representation METS. Which of these are the authoritative and what is the purpose for the two? Are they different?

**Comment by carlwilson** [comment]
Discussed with @karinbredenberg to be resolved following addressing of earlier issues for review.

**Comment by koit** [comment]
**CSIP109 Representation METS pointer** `structMap/div/div/mptr` description currently reads:

>The division (div) of the specific representation includes one occurrence of the METS pointer (mptr) element, pointing to the appropriate representation METS file.

In the case of a METS.xml in a representation folder, this requirement creates a circular reference back to the same METS.xml file. Instead, only parent METS files should point to their child METS files.

I propose changing it, involving 3 steps.

### 1. Change the description of CSIP109 to:

>mptr elements are used in parent METS.xml files to point to their child METS.xml files. For the METS document in the root folder of the package, the division (div) of the specific representation includes one occurrence of the METS pointer (mptr) element, pointing to the appropriate representation METS file. For a METS document in a representation folder, mptr is used only if the representation also contains other METS.xml files, in which case the representation root METS.xml has an mptr for each child METS.xml. 

### 2. Change the sentence in intro text of section 5.3.6

Current text:

>The structural map in the representations METS file use the structural map the same way with no exceptions

Change to:

>Representations METS files use structural map the same way, with the exceptions described below.

### 3. Change cardinality of CSIP109

Cardinality should be changed from 1..1 to 0..n.

**Comment by koit** [comment]
Is it explicitly required to have a METS.xml in the representation? E.g. in a package with only one rep, all of the METS stuff could be presented in the root METS.xml.
