### ISSUE TITLE
CSIP101 Clarify structMap requirements for File division

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#427]
The wording of CSIP101 `structMap/div/div` is still fuzzy (we experienced this when trying to strictly follow all the rules to create minimal valid IPs, see https://github.com/DILCISBoard/eark-ip-test-corpus/pull/211 and https://github.com/DILCISBoard/eark-ip-test-corpus/pull/212).

```xml
<requirement ID="CSIP101" REQLEVEL="SHOULD" EXAMPLES="structMapExample1">
  <description>
    <head>File division</head>
    <p xmlns="http://www.w3.org/1999/xhtml">The transferred files referenced in the file section file group are described in the structural map in a single sub division.</p>
    <p xmlns="http://www.w3.org/1999/xhtml">When the transfer comprises of only data and no representations there should still be a single empty representation div present.</p>
    <dl xmlns="http://www.w3.org/1999/xhtml">
      <dt>METS XPath</dt><dd>structMap/div/div</dd>
      <dt>Cardinality</dt><dd>0..1</dd>
    </dl>
  </description>
</requirement>
```

I propose three improvements.

### 1. Explanation of "File division"

The term "File division" appears suddenly in CSIP101 and is only used in the definitions of CSIP rules 101-104. Before that, there have already been the terms "File section" and "File group", which have been properly explained in the intro of Section **5.3.5. Use of the METS file section (element fileSec)**. Thus, I propose adding an introductory paragraph to CSIP101 description:

"If the IP contains actual content files (as opposed to an IP that only has metadata), the structural relationships of the content files are described in a `structMap/div/div` called "File division.""

Note: the exact wording should reflect the purpose of structMap and this div, see #426.

### 2. "File division" vs "representation division"

Both "File division" and "representation" are used here for the same thing. "Representation division" is a bit confusing, as here it means the root for all representations, but it could also be read as the div for a specific representation. As the `representations` folder became optional, I would ditch "representation div" here and leave only "File division" ("representation div" could then be used for the divisions of individual representations).

Actually, "Content division" or "Content file division" would be even better, as "File division" is ambiguous - both content files and metadata files are files.

### 3. "Transferred files" vs "content files"

"Transfer" implies SIP or DIP, but CSIP is also designed for long term preservation AIPs, so I propose using "content files" or "payload files" or similar (we should agree on one and use it consistently throughout the specification).

PS I used https://github.com/DILCISBoard/E-ARK-CSIP/blob/rel/v2.0-draft/profile/CSIP.xml text with the assumption that this is the right source for requirement texts and the requirements.md files e.g. https://github.com/DILCISBoard/E-ARK-CSIP/blob/rel/v2.0-draft/specification/implementation/metadata/mets/structmap/requirements.md are autogenerated from it.

**Comment by carlwilson** [comment]
Hi @koit I agree with these points and find myself struggling with point 2 at times in particular. Myself and @karinbredenberg are going to review the supporting text for these concepts and ensure that it exists, and that it's as concise and clear as we can make it. We'll get a chance to review the changes in the A3 group.

**Comment by koit** [comment]
An example of the fuzziness: reading the requirements for File division and Representations division (CSIP101, CSIP103, CSIP105, CSIP107) I derived another possible interpretation:

"If the IP has only one representation, it can be regarded as not a representation but as "only data." In that case, there can be a strucMap/div/div for the content, with `@LABEL = "Representations"`, but content files directly in this div, not having their own "rep1" div."

I doubt this was the intent, as the folder structure `representations/rep1/data` used to be mandatory.

In sum, File division and Representations division (CSIP101, CSIP103, CSIP105, CSIP107) have to be considered together to form a coherent whole.
