### ISSUE TITLE
Update examples to use short IDs

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#428]
UUID IDs are very unfriendly to the eye, so I propose using minimal length IDs in the form of "xid-xx", where "xid" could be interpreted as "example ID" or "whatever format ID" and x is [A-Z0-9], so there would be IDs like `xid-01`, `xid-A3`, `xid-8Y`, `xid-BB`. 

For example, instead of the current text:
```xml
<mets:div ID="uuid-A4E1C5B6-CD9B-43EF-8F0C-3FD3AB688F81" LABEL="Metadata" ADMID="uuid-9124DA4D-3736-4F69-8355-EB79A22E943F uuid-48C18DD8-2561-4315-AC39-F941CBB138B3" DMDID="uuid-906F4F12-BA52-4779-AE2C-178F9206111F">
```

we would have this:
```xml
<mets:div ID="xid-A4" LABEL="Metadata" ADMID="xid-91 xid-48" DMDID="xid-90">
```

**Comment by karinbredenberg** [comment]
We wont do this. We need to use a real life example.

**Comment by carlwilson** [comment]
There are considerable shared concerns around readability of the UUIDs (everyone in the A3 group dislikes them).

**Comment by koit** [comment]
I assume the purpose of the examples in the CSIP text is to help readers understand the specification. From this perspective, shorter IDs are preferrable:

- The examples are deliberately artificial to convey the meaning of the requirements in the most efficient way: only the relevant elements are presented in each exerpt, file names are simplified, only a few files are used vs the thousands or millions of real life etc.;
- "xid-xx" format is actually realistic in that it provides a pool of 36^2 = 1296 IDs. In Estonia, we've had several ingests of born-digital content, where the whole transfer was less than 1000 files;
- Long IDs make the example text wider or longer (depending on the wrapping settings), so less text will fit on screen. More text visible at once means easier understanding;
- The IDs are not decorations that can be ignored. Instead, they are pointers that are used to link elements, so the reader must be able remember an ID and quickly spot its other instances. 2-3 abstract symbols is the maximum to effortlessly remember, so UUIDs demand extra effort to first decide on a section to remember and then to ignore the remainder when seeking the matching IDs.

An alternative to the abstract "xid-xx" format would be semantic IDs, e.g. in the example above, the `div/@ID` could be "id-root-mets-structMap-metadata-div". These tend to grow very long, but might speed up understanding of the example, as a reference to an ID is self-evident and will not require actually looking it up. See examples of this approach in these minimal IPs:
- [minimal_IP_with_1_representation](https://github.com/DILCISBoard/eark-ip-test-corpus/tree/min-ip-w-1-rep/corpus/template-ip/minimal_IP_with_1_representation)
- [IP_1rep_SIARD2](https://github.com/DILCISBoard/eark-ip-test-corpus/tree/corpus/example/IP_1rep_SIARD2/corpus/template-ip/IP_1rep_SIARD2)

Between the abstract "xid-xx" and semantic IDs, I'm not sure which is better, but both beat UUIDs for the examples inside the CSIP text. We could have a full METS.xml with UUIDs as another appendix. Similarly, we should also point to full sample IPs that have folder structure and payload files.

See also #256.
