### ISSUE TITLE
CSIP64 fileGrp/USE one-word categories instead of full folder path

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#435]
The current definition of CSIP64 reads:

```xml
<requirement ID="CSIP64" REQLEVEL="MUST" EXAMPLES="fileSecExample1 fileSecExample2">
    <description>
        <head>Description of the use of the file group</head>
        <p xmlns="http://www.w3.org/1999/xhtml">The value in the @USE is the name of the whole folder structure to the data, e.g "Documentation", "Schemas", "Representations/preingest" or "Representations/submission/data".</p>
        <dl xmlns="http://www.w3.org/1999/xhtml">
            <dt>METS XPath</dt><dd>fileSec/fileGrp/@USE</dd>
            <dt>Cardinality</dt><dd>1..1</dd>
        </dl>
    </description>
</requirement>
```

mets.xsd annotation for fileGrpType attribute `@USE` states:
>/…/ A tagging attribute to indicate the intended use of files within this file group (e.g., master, reference, thumbnails for image files)./…/

In this light, having the full path in the `@USE` attribute seems weird because:

1. The path is already present in all child `file/FLocat` elements;
2. `@USE` should describe the use scenario in general, while "Representations/preingest" and "Representations/submission/data" are effectively both representations, so the full path just muddies the water;
3. The paths can get ugly, further exacerbating issue 2, e.g. "Representations/rep1/data/Messages/0T/0B/0M/6K/186K/" as in the Outlook example I provided in #426.

CSIP structMap is about physical structure, so it can provide the structure of file groups.

Going without full paths seems to have been the intention at some point, as the description of  [VocabularyFileGrpAndStructMapDivisionLabel](http://earkcsip.dilcis.eu/#VocabularyFileGrpAndStructMapDivisionLabel) explicitly states `fileGrp/@USE` as its intended use context.

In sum, I propose sticking to the one-word values from VocabularyFileGrpAndStructMapDivisionLabel.

**Comment by carlwilson** [comment]
I'm in favour of fixing this IF it forces paths to be duplicated in a package. Repetition is brittle as it leaves the door open for a change to be made in one place while not reflected elsewhere
