### ISSUE TITLE
Inconsistency - use singular or plural terms in the vocabulary

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#445]
Having just changed value in a corpus from "Database" to the currently correct "Databases"
we noticed that the vocabulary has an inconsistent mix of singular and plural.
E.g. "Databases" but "Physical object" or "Collection".

http://earkcsip.dilcis.eu/schema/DILCISVocabulariesIP.xml 
#https://github.com/DILCISBoard/eark-ip-test-corpus/pull/217

**Comment by karinbredenberg** [comment]
The words comes from the original vocabularies in some cases so they havent been changed.

**Comment by karinbredenberg** [comment]
This is connected to #316 
The terms has not been changed in the move to our value list instead they are following the original used terms.
