### ISSUE TITLE
CSIP2 - Reduce risk of confusion by adding more explanation, change order and possibly change to another name

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#447]
`Content information type specification name` 
and
`Content information type declaration`
are very close and can lead to confusion.

If we cannot find more distinct names now then at least we can change the order so it follows the METS standard, i.e. 
first the general (Content information type declaration)
then the specific (Content information type specification name)

See also #446 

http://earkcsip.dilcis.eu/#controlled-vocabularies

Content information type specification name

Maintained By: DILCIS Board
Location: http://earkcsip.dilcis.eu/schema/
Context: Used in @csip:CONTENTINFORMATIONTYPE
Description:
Describes the specific E-ARK content information type names supported or maintained in this METS profile.

Content information type declaration

Maintained By: DILCIS Board
Location: http://earkcsip.dilcis.eu/schema/
Context: Used in mets/@type
Description:
Describes the broad information type classification

**Comment by karinbredenberg** [comment]
Names have changed. Order of vocabularies havent.
