### ISSUE TITLE
Fix typos and improve wording in CSIP71, CSIP87, CSIP91

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#454]
Make the following changes in [CSIP.xml](https://github.com/DILCISBoard/E-ARK-CSIP/blob/rel/v2.0-draft/profile/CSIP.xml):

---

### **CSIP71 File checksum** `fileSec/fileGrp/file/@CHECKSUM`

Change the line:

```xml
<dt>MES XPath</dt><dd>fileSec/fileGrp/file/@CHECKSUM</dd>
```

to:

```xml
<dt>METS XPath</dt><dd>fileSec/fileGrp/file/@CHECKSUM</dd>
```

---

### **CSIP87 Sub structural division** `structMap/div/div`

Change the line:

```xml
<p xmlns="http://www.w3.org/1999/xhtml">Each catagorisation "Documentation", "Schemas" as well as each "Representation" within the package must be represented by an occurrence of the division (div) element.</p>
```

to:

```xml
<p xmlns="http://www.w3.org/1999/xhtml">Each categorisation "Documentation", "Schemas", as well as each "Representation" within the package must be represented by an occurrence of the division (div) element.</p>
```

---

### **CSIP91 Metadata division administrative metadata referencing** `structMap/div/div/@ADMID`

Meaning unclear, needs rewording:

>All administrative metadata described in the package are referenced via the administrative sections different identifiers.

**Comment by karinbredenberg** [comment]
CSIP71, CSIP87CSIP91 has been rewritten.
