### ISSUE TITLE
dmdSec/mdWrap

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#47]
We don't recommend the use so we should not have it described here. Its up to the local implementation to specify it. We can leave this first element saying its an option that needs to be evaluated in the implementation and remove all the rest of the elements regarding mdWrap.

**Comment by karinbredenberg** [comment]
Making the suggested change makes the linked issues obsolete #59 #58 #57 #56 #55 #54 #53 #52 #51 #50 #49 #48

**Comment by kuldaraas** [comment]
Removed
