### ISSUE TITLE
Creating METS profiles for CSIP, SIP, AIP and DIP

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#530]
Where are we with the METS profiles for CSIP, SIP, AIP and DIP?
I assume the METS profile for CSIP is (at least partly) autogenerated from the index.md.
Where is the tool (script) we are using for that?

**Comment by karinbredenberg** [comment]
Its the other way around. The tables are generated from the profile. CSIP and SIP has a profile created already. So the profile needs to be created manually.

**Comment by andersbonielsen** [comment]
Fine, then we do it the other way round, but where is the script going from xml to GitHub MD? Or
did you just do it partly manually?
And where is the profile for the AIP that we need to base the DIP profile on?
So far we only have a draft DIP profile based on the CSIP profile.

**Comment by karinbredenberg** [comment]
@carlwilson have the links to the script.
Not sure the AIP has a profile it looks like it is the CSIP used as is.
But the beest is if its based upon the CSIP, you see all the linkage between the two in the SIP profile.

**Comment by carlwilson** [comment]
Given that the AIP in its current form won't ever have a validation profile and the others are done we're closing this issue.
