### ISSUE TITLE
MAJOR case inconsistency between text and figures

### ISSUE THREAD

**Issue by hsilva-keep** [DILCISBoard/E-ARK-CSIP#555]
There is a case inconsistency between images and text in section [4.1. Folder structure of the CSIP](https://earkcsip.dilcis.eu/#41-folder-structure-of-the-csip) and section [4.2. Implementing the structure](https://earkcsip.dilcis.eu/#42-implementing-the-structure), as well as text and examples of sections [5.3.3 Use of the METS descriptive metadata section (element dmdSec)](https://earkcsip.dilcis.eu/#533-use-of-the-mets-descriptive-metadata-section-element-dmdsec), [5.3.4. Use of the METS administrative metadata section (element amdSec)](https://earkcsip.dilcis.eu/#534-use-of-the-mets-administrative-metadata-section-element-amdsec), [5.3.5. Use of the METS file section (element fileSec)](https://earkcsip.dilcis.eu/#535-use-of-the-mets-file-section-element-filesec) and [5.3.6. Use of the METS structural map (\<structMap\>)](https://earkcsip.dilcis.eu/#536-use-of-the-mets-structural-map-structmap).

In some places lowercase is used to mention metadata, data, schemas, documentation and/or representations folder's, in others upper case (i.e. Schemas, Documentation, etc.), in others both:
```xml
<mets:fileGrp ID="uuid-5811D494-6045-4741-924C-A1CFA340C279" USE="Representations/ingest/data" ... >
    <mets:file ID="uuid-EE23344D-4F64-40C1-8E18-75839EF661FG"... >
      <mets:FLocat LOCTYPE="URL" type="simple" href="representations/ingest/METS.xml">
      </mets:FLocat>
    </mets:file>
  </mets:fileGrp>
```

Vocabulary file https://earkcsip.dilcis.eu/schema/CSIPVocabularyFileGrpAndStructMapDivisionLabel.xml uses first letter upper case logic.

And this matter is of **MAJOR** importance because 1) makes it harder to be version 2.0.0 compliant when compliance with version 1.0.0 already exists; 2) it's confusing for someone reading the specification for implementing it and sees all these case inconsistencies.

And also we wonder why this has changed from previous major version as keeping everything in lower case makes things consistent between folders and METS attributes (both LABEL & USE).

**Comment by hsilva-keep** [comment]
Actually every single example (full or excerpt) and image must be checked as more inconsistencies do exists besides the ones I've mentioned in the issue description.

**Comment by karinbredenberg** [comment]
We'll look into it and make updates, it wont be released right away though.

**Comment by hsilva-keep** [comment]
@karinbredenberg thank you...for us the release is not important as we only need to have a clear understanding about the changes needed on the software side.

**Comment by karinbredenberg** [comment]
Ok, @hsilva-keep you also need to keep in mind that the @USE and @LABEL is part of a vocabulary so it is not a easy change. Making sure in a first round that the vocabulary is used in all the places. (LABEL for representations uses the full path to the representation.)

**Comment by hsilva-keep** [comment]
@karinbredenberg As I commented before in this issue, I just wonder why this has changed from previous major version as keeping everything in lower case makes things consistent between folders and METS attributes (both LABEL & USE).

**Comment by karinbredenberg** [comment]
There were a decision of having capital starting in the vocabularies.

**Comment by hsilva-keep** [comment]
@karinbredenberg was that decision made on an A2 meeting or Github issue? Because lots of things have changed in the last weeks before the release (end of May), which do impact in the amount of changes required in the tools for them to be CSIP 2.0 compliant.

Nevertheless, we will wait for the text update.

**Comment by karinbredenberg** [comment]
We have now made sure that the examples of the attributes USE and LABEL are consistent and start with upper case and that all folder and file paths given in hrefs are in lowercase and that the folders in the images use lower case. 

There are things to have in mind, the USE and LABEL don’t give a catalogue/folder name or file path unless it’s a specific representation being described to give the description of which representation it is. I can agree that these names that have been chosen aren’t the best and we should find better names describing the content that are housed in these filegroups and structMap div’s than ones using the file path. And perhaps the USE and LABEL for the different representations should just have the value “Representations” and not specify which one of the representations it is. 

All in all, we need to revisit this and come up with better terms to put into the USE and LABEL attributes and at the same time we also need to give better explanations in the guide line that will be developed to what the USE and LABEL attributes are for (describing what’s housed in the file group and structMap div) All this is for the next version though.

**Comment by carlwilson** [comment]
Case inconsistencies in tables and diagrams should be fixed in v2.0.1 @hsilva-keep

**Comment by carlwilson** [comment]
Ready to close

**Comment by karinbredenberg** [comment]
Agree, ready to close.
