### ISSUE TITLE
Content Information Type Specification for Relational Databases vs. E-ARK SIARD

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#557]
https://earkcsip.dilcis.eu/#12-the-common-specification-for-information-packages-and-content-information-type-specifications states that there is a Content Information Type called E-ARK SIARD.
I believe the correct CITS is:
Content Information Type Specification for Relational Databases

**Comment by karinbredenberg** [comment]
Thanks for catching that! Gets fixed today.
