### ISSUE TITLE
Clarification on Representation Metadata

### ISSUE THREAD

**Issue by kalmicka** [DILCISBoard/E-ARK-CSIP#568]
Hey there, 
first of all thanks for the great work on the whole project! I do, however, have some difficulties in understanding some of the documentation. On page 31 of Version 2.0.0 you write

> It is worth noting, to avoid confusion, that we recommend adoption of a common approach, either adding metadata to representations or not. That is, we recommend placing all representation-relevant metadata in a single location. You may use either the package level metadata folder or the representation level metadata folder, but do not divide metadata between the two inconsistently, with representation metadata stored at both package and representation level.

This leads me to believe that metadata should either be on the root level or in each representation level metadata folder. However, in figure 10, where you showcase the full use of the CSIP Structure there is metadata in the root level (Premis1.xml, Premis2.xml) and in the representation level metadata folder (Premis_R1.xml). Is this correct? In the example that is given there is no metdata included in the representation level metadata folder. What seems to be correct or am I just not getting it? 
Thanks in advance

**Comment by karinbredenberg** [comment]
Thank you and thank you for your question. 

On the root level there is metadata pertaining to the root level and in the representations is the metadata pertaining to the different representations. Meaning its not the same metadata stored in the different levels. The important thing is to be consistent.

We'll make sure to explain this in more depth in the guideline that will be created.
