### ISSUE TITLE
Clarification of principle 1.3

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#569]
Clarification needed in a guideline:
In principle 1.3 the sentence "One of the fundamental principles of the CSIP is that it MUST allow each individual repository to define the (intellectual) scope of an Information Package and its relations to real life entities." wasn't clear to us.  Does "relations to real live entities" refer to the analogous object which was digitized or to the general basic conditions of the archive?

**Comment by karinbredenberg** [comment]
The answer is to the analog object. 

Need to add definition of intellectual in regard to IP in the guideline.

**Comment by carlwilson** [comment]
Fixed in Guidelines release.
