### ISSUE TITLE
Make sure all releases are tagged

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#590]
All releases needs to show up in the list of releases.

For all IP's.

**Comment by carlwilson** [comment]
Releases are tagged across specifications, we may want to make releases up from them? There's also the question of what to do about specifications we don't change. The AIP is still effectively 2.0.1 and the DIP is 2.0.2.

**Comment by karinbredenberg** [comment]
Ok, we need to make sure we have all releases on the release page. So no ones for not changed ones, but for all which have changes there needs to be a release saved.
