### ISSUE TITLE
Update of the common introduction text in the specifications

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#592]
The common text needs some updates.
Pertains to all the specifications.
@DrJaime needs guidiance from @carlwilson on how to do it.

**Comment by carlwilson** [comment]
This is fine. The current solution suited production but isn't ideal for editing. This is on me to improve and pass @DrJaime the details once I'm done.

**Comment by carlwilson** [comment]
@DrJaime , the text for this is in the specification project and will need updating in [this folder](https://github.com/DILCISBoard/spec-publisher/tree/master/res/md), or this file specifically: https://github.com/DILCISBoard/spec-publisher/blob/master/res/md/common-intro.md

**Comment by karinbredenberg** [comment]
Use the Git interface to make the change @DrJaime
