### ISSUE TITLE
Review the use of the attribute @CONTENTTYPESPECIFICATION

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#6]
If we have more than one representation, the proposed vocabulary does not make sense. For example, we can have an AIP with two representations with a SIARD2 and a SIARD2.1.

**Comment by PhillipTommerholt** [comment]
I agree with Miguel. 
Even if we say that this attribute should only be at representation level, then there can be scenarios where the representation also contain several content information types (_It could be an ERMS submitted as a relational database, or a relational database with geodata or any other combo._)

Regarding Content Information Type as a vocabulary or classification we must be cautious about how we treat: 
- the  mutual exclusiveness of categories ( can one object only be placed in one category within the whole classification universe) ?
- collectively exhaustivity (an object must be able to be placed in a meaningful category in the classification universe) ?

If we use an attribute to determine "what kind" a representation is, then we lock ourselves in a way that there is (or should be) a classification universe. I don't think we are anywhere near to be able to create such a universe and nor do we have the resources or plan to maintain it.

I suggest that Content Information Type should be described as free text in an element. Then the different Content Information Type Specifications specify what the specific value should be within this element.

**Comment by karinbredenberg** [comment]
More investigation needed. Connected with #10

**Comment by karinbredenberg** [comment]
Vocabulary contains both values MIXED and OTHER so all possibilities of describing the content is present.
