### ISSUE TITLE
amdSec/rightsMD

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#63]
We recommend a simple use we need to have rules for the simple rules and point to them

**Comment by kuldaraas** [comment]
Up for discussion with the DILCIS Board

**Comment by karinbredenberg** [comment]
Addition of elements to use when using the elements and pointers to possible schemas to use needs to be added.

**Comment by karinbredenberg** [comment]
Description added.
