### ISSUE TITLE
CSIPSTR16: There is no mention of Representation Information. We should add this to the examples.

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#632]
Guys, 

I can't seem to find this change discussed in #595 reflected in the latest version.. I'm looking at the wrong version?

<img width="1792" alt="Screenshot 2020-06-17 at 09 30 15" src="https://user-images.githubusercontent.com/3181302/84874958-3ed88800-b07d-11ea-8c96-4e9ae8ea3c54.png">

The final sentence is missing: 

> Examples of documentation include representation information and manuals for the system the data objects were exported from.

_Originally posted by @jmaferreira in https://github.com/DILCISBoard/E-ARK-CSIP/pull/595#issuecomment-645234456_

**Comment by karinbredenberg** [comment]
Hmpfr, that seems to have been lost in PR world.

**Comment by carlwilson** [comment]
@carlwilson and @karinbredenberg to check wording for the upcoming release.

**Comment by karinbredenberg** [comment]
Available in PR #595 @carlwilson

**Comment by karinbredenberg** [comment]
Closed with PR #680
