### ISSUE TITLE
Suggestion to remove heading "5.3.1.1. Location of XML schema"

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#635]
This is just a suggestion.

Section 5.3.1.1. has no siblings. It represents unnecessary nesting.
The heading could be removed and make its text be part of 5.3.1. 

<img width="1792" alt="Screenshot 2020-06-17 at 09 49 20" src="https://user-images.githubusercontent.com/3181302/84877003-d7700780-b07f-11ea-9907-ed183647d84e.png">

**Comment by karinbredenberg** [comment]
Closed with PR #668
