### ISSUE TITLE
There is no obvious link between the DILCIS website and the specifications microsites

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#638]
If there is a link, I couldn't find it. The way it stands now propitiates incoherences in versions and aspect.

What I mean is that the DILCIS website has their own pages for each of the SPECS, and simultaneously, there are microsites that are always up-to-date with the latest version of the specs. 

<img width="1792" alt="Screenshot 2020-06-17 at 10 11 11" src="https://user-images.githubusercontent.com/3181302/84879260-e3a99400-b082-11ea-8a01-2304212e1fa1.png">

Can we make both point to the same information so that we eliminate incoherences?

<img width="1792" alt="Screenshot 2020-06-17 at 10 09 42" src="https://user-images.githubusercontent.com/3181302/84879131-b6f57c80-b082-11ea-813f-3cdbcad07ba0.png">

As you can see from the examples, the microsite is already on version 2.0.4-DRAFT and the DILCIS site is still on 2.0.0.

**Comment by karinbredenberg** [comment]
That's since I havent had the chance to send the request to get the DILCIS webpage updated. Its on its way.

**Comment by carlwilson** [comment]
Fixed.
