### ISSUE TITLE
CSIP2 - example values should be from the vocabulary

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#639]
A snippet of the CSIP2 requirement goes like this:
`The mets/@TYPE attribute MUST be used to declare the category of the content held in the package, e.g. book, journal, stereograph, video, etc.. Legal values are defined in a fixed vocabulary.`

But if I go to the vocabulary then the examples in the snippet does not exist.

I propose something like this requirement text:
`The mets/@TYPE attribute MUST be used to declare the category of the content held in the package, e.g. datasets, websites, mixed, other, etc.. Legal values are defined in a fixed vocabulary.`

**Comment by karinbredenberg** [comment]
Good catch, the text has not been updated. A fix for next version.

**Comment by karinbredenberg** [comment]
Closed with PR #669
