### ISSUE TITLE
Request for change in the "Content Information Type"-vocabulary (and handling of SIARD spec versions)

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#641]
The current vocabulary https://earkcsip.dilcis.eu/schema/CSIPVocabularyContentInformationType.xml has three different SIARD values:
SIARD1, SIARD2 and SIARDDK. 

I propose it should have only only legal value: CITS_SIARD

Then I will let the CITS SIARD specification deal with the more exact version of the SIARD specification at the file level.
So if a METS.xml describes a CITS_SIARD in the mets/@csip:CONTENTINFORMATIONTYPE then there need to be 

1. a link to minimum another representation METS.xml
or
2. minimum a file with the attribute csip:OTHERCONTENTTYPESPECIFICATION with a value from a CITS SIARD vocbulary. The current values I see is: {SIARD_1.0, SIARD_2.0, SIARD_2.1, SIARDDK_1007, SIARDDK_128}

I like this solution since it makes sure that it is the CITS SIARD spec that deals with the vocabulary and that the CSIP does not need to know or make changes everytime there is changes in how many variants there are. I think this might be a principle for all the CITS?

**Comment by PhillipTommerholt** [comment]
It has impact on CSIP5 if we allow othercontenttypespecification to be present together with a value from the vocabulary for contentinformationtype

**Comment by karinbredenberg** [comment]
We need to be careful with removing values since it makes it not backwards compatible. Adding is easier. I'm reluctant to change CSIP5, the if-then will not be easy to handle and we need to have all future CITS in mind here. Stating in the CITS SIARD that the csip:OTHERCONTENTTYPESPECIFICATION needs to be used is not a problem.

**Comment by PhillipTommerholt** [comment]
> We need to be careful with removing values since it makes it not backwards compatible. Adding is easier. I'm reluctant to change CSIP5, the if-then will not be easy to handle and we need to have all future CITS in mind here. Stating in the CITS SIARD that the csip:OTHERCONTENTTYPESPECIFICATION needs to be used is not a problem.

Yes - I read the requirement again and can see it is not a problem - and I agree that we should not remove existing values (how could I suggest that? :) )

**Comment by carlwilson** [comment]
Believe that this can be closed now.
