### ISSUE TITLE
CSIP11 alternative roles for metsHdr/agent

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#646]
CSIP11 `mets/metsHdr/agent[@ROLE='CREATOR']` in CSIP allows only the value `CREATOR`, while mets.xsd also allows `EDITOR, ARCHIVIST, PRESERVATION, DISSEMINATOR, CUSTODIAN, IPOWNER` and `OTHER`. So the current wording of CSIP implies that no agent with a role other than `CREATOR` can be described even if there are multiple `agent` elements.

Is this the intended result? Or do we want that there is always one `agent` with the role `CREATOR`, but there can also be other agents with other roles? This would be analogous to `structMap`, where we mandate one with `mets/structMap[@TYPE='PHYSICAL']`, but allow for others with different types.

**Comment by koit** [comment]
@karinbredenberg, can you please give an opinion on this issue, as CSIP11 - CSIP16 test cases depend on it. The core question: is `mets/metsHdr/agent` analogous to `mets/structMap` in that one instance is mandatory (with strict characteristics) and other instances are up to the user deliberation with no restrictions to mets.xsd?

**Comment by karinbredenberg** [comment]
Yes there is one mandatory agent with the agent role being "CREATOR" and the type being "OTHER" and othertype being "SOFTWARE". As written in CSIP10 there can be local agents added but the "CREATOR" one is mandatory.

**Comment by carlwilson** [comment]
I think that this is cleared up (other agents are possible, just not mandatory). Closing.
