### ISSUE TITLE
CSIP80 - how to determine the CSIP structMap?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#648]
CSIP80 states that "Each METS file must include ONE structural map <structMap> element used exactly as described here." and then follows all the requirements for structMap.
The problem with the formulation of CSIP80 is that there is no way to determine if a structMap element is meant to live up to requirements CSIP81-112. There might be two structMap elements which only partially live up to the requirements and how would a validator know which one to validate?
In the testcase https://github.com/DILCISBoard/eark-ip-test-corpus/pull/229/commits/9710696f5581df2183738bd04a7a156f85088b02 I have tried to combine CSIP82 and CSIP80 so that it is the mets/structMap[@LABEL='CSIP'] that determines that this is indeed a structMap-element that it stated to live up to all the requirements. 

I suggest a reformulation of CSIP80 to something like:
```
Structural description of the package
mets/structMap
The <structMap> in the CSIP describes the highest logical structure of the IP.
Each METS file must include ONE structural map <structMap> element used exactly as described in the following requirements regarding the <structMap>
The way to identify the <structMap> element which follows all the structMap requirements is given in CSIP82.
Institutions can add their own additional custom structural maps as separate <structMap> sections. 
```

**Comment by karinbredenberg** [comment]
Closed with PR #676
