### ISSUE TITLE
CSIP105 - suggestion for reformulation

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#653]
CSIP105 states:
`When a package consists of multiple representations, each described by a representation level METS.xml document, there is a discrete representation div element for each representation.`

I would suggest reformulation to something like:
`When a package consists of one or more representations, which are described by a representation level METS.xml document, there SHOULD be a discrete representation div element for each representation.`

Would it not be more correct?

**Comment by karinbredenberg** [comment]
Closed with PR #675
