### ISSUE TITLE
Can the USE-attribute be used on file level?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#654]
For a fileGrp there MUST be a USE-attribute with defined values such as "Documentation" or "Schemas" etc. 
Files within this filGrp can themselves also have USE-attributes.
There are no rules on how to use the USE-attributes on file elements within fileGrps - should there be?

**Comment by karinbredenberg** [comment]
The Use attribute on the file level dont need a rule.
