### ISSUE TITLE
"Conditional MUST" needs better explanation

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#657]
There are many instances of "Conditional MUST" that are confusing to the reader. Several kinds exist:
- a SHOULD requirement that depends on a certain value of a MUST requirement, e.g. CSIP3 and 2;
- a MAY requirement that depends on a certain value of a SHOULD requirement, e.g. CSIP5 and 4;
- a MUST requirement that depends on the existence of a SHOULD-level element, e.g. CSIP33 and 32, and the flavour of it where both have the same XPath, e.g. CSIP99 and 97 (see also #570);
- a MUST requirement that depends on the existence of a MAY-level element, e.g. CSIP46 and 45;
- a SHOULD requirement that depends on the existence of a MAY-level element, e.g. CSIP47 and 45;
- a SHOULD requirement that has a condition in itself, e.g. CSIP8;
- a MUST requirement that has a SHOULD in itself, e.g. CSIP113;
- a SHOULD requirement that depends on a MUST requirement that has a secondary dependence, e.g. CSIP97 and 113.

All of these are actually "conditional MUST":
- if the precondition is met, the dependent requirements MUST be met;
- if the precondition is not met, the dependent requirements are SHOULD, MAY or MUST NOT (the latter in the sense that they cannot be met, e.g. `rightsMD/@ID` cannot exist if `rightsMD` does not exist).

While most of these do have a sound logic, it takes a lot of effort to learn that logic. The solution could be an explanatory paragraph somewhere before the METS requirements (e.g. in chapter 5.3) or improved descriptions of each of the specific requirements.

PS The above is valid for CSIP v.2.0.4.

**Comment by PhillipTommerholt** [comment]
Good work, Koit. I agree. I think a visually logic could help - for example by indentation.

**Comment by karinbredenberg** [comment]
Closed with PR #691
