### ISSUE TITLE
CSIPSTR3 should maybe not mention Submission Agreement?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#659]
CSIPSTR3  states that:

> CSIPSTR3: The Information Package root folder MAY be compressed (for example by using TAR or ZIP). Which specific compression format to use needs to be stated in the Submission Agreement.

What if the Producer sends the information package compressed according to the Submission Agreement, and the archive (or another archive) choses to preserve it in another compression at a later point? Where should this information be specified? I think there might be a requirement that the archive SHOULD register the compression of the information packages in their holding or something like that.

I think it might make sense to have this extra requirement about the Submission Agreement at the SIP specification level and not at the CSIP level.  The SIP specification should further specify how it needs to be stated in the Submission Agreement. What would you say @jmaferreira ?

**Comment by karinbredenberg** [comment]
Maybe change to:
CSIPSTR3: The Information Package root folder MAY be compressed (for example by using TAR or ZIP). Which specific compression format to use in the transfer moment should be stated in the Submission Agreement.

This means that we do not change the CSIPSTR3 more than say when it should be in the submission agreement, might that work @carlwilson ?

**Comment by karinbredenberg** [comment]
Closed with PR #685
