### ISSUE TITLE
CSIP96 and CSIP100: obligation MUST but cardinality 0..n

### ISSUE THREAD

**Issue by nvanderperren** [DILCISBoard/E-ARK-CSIP#699]
CSIP96 and CSIP100 have the obligation of MUST, but the cardinality is 0..n. That seems contradictory.

**Comment by karinbredenberg** [comment]
Thanks for catching that! We will look through all of the similar requirements.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

- Update of wording with this PR suggestion #720  

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by karinbredenberg** [comment]
7 DILCIS Board members have acknowledge the issue
7 DILCIS Board members agree with the solution

The PR will be part of the next release of the specifications

**Comment by karinbredenberg** [comment]
Change implemented.
