### ISSUE TITLE
Uniqueness scope of identifiers

### ISSUE THREAD

**Issue by prettybits** [DILCISBoard/E-ARK-CSIP#702]
It is somewhat unclear to me what the intended uniqueness scope of XML identifiers is meant to be. Judging from issue [#63](https://github.com/DILCISBoard/eark-ip-test-corpus/issues/63) in the test corpus and the [description](https://github.com/DILCISBoard/eark-ip-test-corpus/blob/integration/corpora/csip/metadata/structmap/CSIP106/testCase.xml#L17C16-L17C150) of the test case for CSIP106 I get the impression this is only about the general rules for XML identifiers and thus only need to be unique within an XML document?

All the rules about identifiers say this in their description:
> It must be unique within the package.

Which may be the reason why I'm currently getting validation errors in `commons-ip` due to conflicting identifiers across package and representation METS documents (for requirement CSIP106 in the concrete case) as this could be read to apply to the package as a whole and not just _within the package METS_ OR _within the representation METS_. If this is not meant to apply across documents maybe the wording could be adjusted?

I haven't opened an issue in the `commons-ip` repo yet while I'm unsure what interpretation is really correct.

**Comment by karinbredenberg** [comment]
Yes, the ID needs to be unique within the ID's in the METS document. I'll look into the wording.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

- Update of wording with this PR suggestion #716   

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by karinbredenberg** [comment]
7 DILCIS Board members have acknowledge the issue
7 DILCIS Board members agree with the solution

The PR will be part of the next release of the specifications
