### ISSUE TITLE
Agent notes / additional information

### ISSUE THREAD

**Issue by prettybits** [DILCISBoard/E-ARK-CSIP#705]
I'm having a hard time understanding the intent behind the rules concerning agents' notes elements.

As a starting point METS allows an unbounded number of note elements on an agent which I initially expected to remain the case for any agent further defined in the specs here. But CSIP15 is defined as MUST with cardinality `1..1` and not `1..n`, I assume what this really wants to express is that there MUST be one note with the `@csip:NOTETYPE` attribute to record the `SOFTWARE VERSION` as specified in CSIP16 and not actually prohibiting further `note` elements?

SIP13, SIP19 and SIP30 then are defined as MAY with cardinality `0..1` and not `0..n` for the archival creator, submitting and preservation agents respectively to allow for the addition of a note to record an identification code, again I believe not with the intent to actually prohibit more notes? SIP25 for the contact person agent then does not  specify the possibility of recording an identification code and lists the cardinality as `1..*`.

I'm thinking that allowing a note element for an optional identification code could ultimately make sense for _any_ agent, including the creating software. And the cardinalities are only meant to apply to notes with the additional attribute defined after, not note elements generally, but the written specification reads as restricting that, which reflects in how the test cases are currently written and how commons-ip currently validates.

I'd be happy for any clarifications.

**Comment by karinbredenberg** [comment]
Yes, whats stated are the mandatory and optional agents to use when following CSIP. If you want to add more agents you need to write your own extension to CSIP+SIP.

I'll look into the wording.

**Comment by karinbredenberg** [comment]
Yes, thats why I say I need to look into the wording since the stated notes elements are the ones we say that should be used not that you according to METS can have unlimited amount of note elements. If you want more note elements to be used that is something that you say and that's when you need to state it in an extension.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

- Update of wording with this PR suggestion #718  

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by jmaferreira** [comment]
After reading the suggestion up for voting, I'm not sure it fully addresses the reported issue.

**Comment by karinbredenberg** [comment]
7 DILCIS Board members have acknowledge the issue
6 DILCIS Board members agree with the solution

The PR will be part of the next release of the specifications
