### ISSUE TITLE
Principle 4.1 in its current wording conflicts with principle 1.1

### ISSUE THREAD

**Issue by stephenmackey** [DILCISBoard/E-ARK-CSIP#706]
Principle 1.1 states that "it must be possible to include any data or metadata in an information package regardless of its type or format" but principle 4.1 states that "metadata in the information package must conform to a standard". The text for principle 4.1 introduces the concept of "crucial metadata". Does 4.1 only apply to "crucial metadata"? In which case the principle needs to be more specific and in order for validation not to be problematic, acceptable "crucial metadata" standards need to be defined. Is "crucial metadata" the only metadata allowed in the /metadata folder?

**Comment by karinbredenberg** [comment]
When it was written principle 4.1 was for the crucial metadata but of course there can be other metadata.

This will be put on the agenda for the DILCIS Board.

**Comment by stephenmackey** [comment]
Hej Karin

I have been analysing the existing CITS and I do see consistency in the placement of standardised vs non-standardised metadata, so will make appropriate changes in eHealth1 and note for 3D. One question; if there is non-standardised metadata, say techmd placed in a sub-folder in rep/data, should we refer to it in the dmdSec of the mets file?

Other than this I would also like to discuss Archival collections, this is likely a requirement for 3D Product Models (i.e. product assembly structures) and I am envisaging a master metadata only AIP which holds a product structure.

Also, my analysis of the current CITS has given me a good checklist of possible extension points and constraints for a new CITS. Is this useful for the Guideline?

Again also, I have identified anomalies and improvement points for CITS as well as for eHealth1, e,g, folder naming in eHealth2. Should I just raise these as issues in GitHub?

Thanks

Stephen


Stephen Mackey
Senior Consultant
Penwern Limited
+33 668 397 453
***@***.***

**Comment by karinbredenberg** [comment]
The issue have been discussed on todays DILCIS Board meeting and we agreed upon editing the wording so its a well-formed format instead. An update of the wording will be made and a PR will be made for the DILCIS Board to review later on.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

- Update of wording with this PR suggestion #717 

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by karinbredenberg** [comment]
7 DILCIS Board members have acknowledge the issue
7 DILCIS Board members agree with the solution

The PR will be part of the next release of the specifications
