### ISSUE TITLE
Formatting/publication information to be recorded externally

### ISSUE THREAD

**Issue by carlwilson** [DILCISBoard/E-ARK-CSIP#708]
Regarding recording publication/formatting information in the schema. It has been decided that this should be external to the METS Profile. Indeed it may be that it is time to adopt a full publication technology (XSLT?) for this rather than develop further custom code.

**Comment by karinbredenberg** [comment]
The issue have is going to be discussed by the DILCIS Board

**Comment by jmaferreira** [comment]
@carlwilson Can you provide more information regarding this topic? What do you mean by "publication/formatting information"?

There is a technology called XML-FO that can be used to transform XML files into page oriented digital documents such as PDF files. Is this what we are talking about?

**Comment by stephenmackey** [comment]
I don't understand what issue is being addressed here.

**Comment by karinbredenberg** [comment]
This is about the overall technical way of creating the publications.

**Comment by carlwilson** [comment]
> @carlwilson Can you provide more information regarding this topic? What do you mean by "publication/formatting information"?
> 
> There is a technology called XML-FO that can be used to transform XML files into page oriented digital documents such as PDF files. Is this what we are talking about?

We currently have two forms of publication, the web site and the PDF. I'm working to replace the current publication code with a combination of XSLT (Web site) and XMF-FO for the PDF. The deadline for the new flow is by the middle of march.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

- Update the publication process to use GitHub actions and XSLT

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by karinbredenberg** [comment]
7 DILCIS Board members have acknowledge the issue
7 DILCIS Board members agree with the solution

The suggestion of updated publication enhancements will be part of the next release of the specifications

**Comment by karinbredenberg** [comment]
Change implemented.
