### ISSUE TITLE
fileSec

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#71]
A must in case we don't put some where that only dmdSec and/or amdSec can be used

**Comment by karinbredenberg** [comment]
Can be omitted since we sy that there needs to be a fileGrp present.

**Comment by karinbredenberg** [comment]
Can we just use dmdSec and amdSec? How do we then use structmap?

**Comment by kuldaraas** [comment]
Yes, I would not outrule that there are valid delta packages which provide updates to the metadata portion of an IP and as such do not include content files.

**Comment by karinbredenberg** [comment]
Then we need another type of structMap than the one we currently have since its the mandatory element.

**Comment by karinbredenberg** [comment]
Connected to #83 and #85

**Comment by karinbredenberg** [comment]
Handled.
