### ISSUE TITLE
Alignment between the Vocabulary Content Category list and LOC Recommended Formats Statement

### ISSUE THREAD

**Issue by mielvds** [DILCISBoard/E-ARK-CSIP#713]
Hello! 

The values in https://earkcsip.dilcis.eu/schema/CSIPVocabularyContentCategory.xml are derived from https://www.loc.gov/preservation/resources/rfs/TOC.html. 

I had two questions about these:

1. We noticed that the hypen character from https://www.loc.gov/preservation/resources/rfs/TOC.html got turned into a m-dash character in https://earkcsip.dilcis.eu/schema/CSIPVocabularyContentCategory.xml. Was this intentional? Although not ideal, we do some string matching on the value of `@TYPE` and it can cause problems along the way.

2. Some values from https://www.loc.gov/preservation/resources/rfs/TOC.html are missing. Are there plans to eventually add those as well or are they left out on purpose? We have some use cases that would require for instance ["Scanned 3D Objects (output from photogrammetry scanning)"](https://www.loc.gov/preservation/resources/rfs/design3D.html#scanned-3d)

Cheers!

**Comment by karinbredenberg** [comment]
Thank you for you comment!

The list was created in around 2017 and the type of dash followed the LoC page at that time as did the values. 

Changes of type of dash might cause other problems but we will look into that!

Addition of missing LoC values will be suggested.

A plan for an update will be setup by the DILCIS Board.

**Comment by karinbredenberg** [comment]
**The suggestion is:**

- Register a new issue with change of the hypen to be handled in the next mayor revision
- Add the values from https://www.loc.gov/preservation/resources/rfs/TOC.html  not currently in the list

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [ ] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [ ] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [ ] Stephen Mackey (Penwern Limited)
- [ ] Sven Schlarb (Austrian Institute of Technology)

**Comment by karinbredenberg** [comment]
7 DILCIS Board members have acknowledge the issue
7 DILCIS Board members agree with the solution

The suggestion of updated list will be part of the next release of the specifications.

A new issue will be created for the hyphen which will need to be part of the next major revision.

**Comment by mielvds** [comment]
Hi @karinbredenberg , has the issue for the hyphen been created yet, or should I go ahead?
There is also no milestone for next major version 3.0 yet

**Comment by karinbredenberg** [comment]
Change implemented and new issue #735 was created.
