### ISSUE TITLE
fileSec/fileGrp/file/FContent

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#79]
Remove? We dont want the files wraped linked to #58 and #59

**Comment by karinbredenberg** [comment]
Links to #80 and #81

**Comment by kuldaraas** [comment]
@karinbredenberg Remove or state that it must not to be used???

**Comment by karinbredenberg** [comment]
I would remove it.

**Comment by kuldaraas** [comment]
Removed
