### ISSUE TITLE
structMap/div/@ID

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-CSIP#85]
This ID is used for? Remove?

**Comment by kuldaraas** [comment]
Used for referencing to it if needed? The current spec states that it's mandatory, if we remove it becomes by default optional --> need to have a DILCIS Board review of the proposal to remove..

**Comment by karinbredenberg** [comment]
Would say this is a mandatory element in the profile for SIP not for CS IP.

**Comment by karinbredenberg** [comment]
More investigation needed. Connected to issue #83

**Comment by karinbredenberg** [comment]
Handled
